//  PacketTunnelProvider.mm — runs the i2pd daemon inside the VPN extension and
//  points the system at its local HTTP proxy for *.i2p.
//
//  Everything the app displays is written to the shared app-group container:
//    i2pd/          i2pd's data directory (netdb, keys, i2pd.conf)
//    i2pd.log       the daemon log, tailed by the Logs tab
//    status.plist   uptime / tunnel counts, polled by the Home tab

// Apple's AssertMacros.h defines a bare `check` macro that collides with the
// Boost headers the i2pd includes pull in. Opt out of the un-underscored names.
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0

#import "PacketTunnelProvider.h"

#import <Foundation/Foundation.h>

#include <atomic>
#include <chrono>
#include <string>
#include <thread>
#include <vector>

#include <openssl/ssl.h>

#include "Daemon.h"
#include "NetDb.hpp"
#include "RouterContext.h"
#include "Tunnel.h"

static NSString* const kAppGroup = @"group.uk.nouvborne.ios2pd";
static const int kHttpProxyPort = 4444;
static const unsigned long long kMaxLogBytes = 1024 * 1024;

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

// The app reads the log and status out of the shared container. If the group is
// unavailable (a sideloader rewrote the bundle ids), fall back to the
// extension's own container: the router still works, the app just shows nothing.
static NSString* SharedDir(void) {
  NSURL* url = [[NSFileManager defaultManager]
      containerURLForSecurityApplicationGroupIdentifier:kAppGroup];
  return url ? url.path : NSHomeDirectory();
}

static NSString* DataDir(void) {
  NSString* dir = [SharedDir() stringByAppendingPathComponent:@"i2pd"];
  [[NSFileManager defaultManager] createDirectoryAtPath:dir
                           withIntermediateDirectories:YES
                                            attributes:nil
                                                 error:nil];
  return dir;
}

static NSString* LogPath(void) {
  return [SharedDir() stringByAppendingPathComponent:@"i2pd.log"];
}

static NSURL* StatusURL(void) {
  return [NSURL fileURLWithPath:[SharedDir()
                                    stringByAppendingPathComponent:@"status.plist"]];
}

// i2pd appends to its logfile forever, so drop it once it gets large.
// ponytail: truncate-on-connect, not real rotation. Only worth replacing if a
// single session ever needs more than kMaxLogBytes of history.
static void TrimLog(void) {
  NSFileManager* fm = [NSFileManager defaultManager];
  NSDictionary* attrs = [fm attributesOfItemAtPath:LogPath() error:nil];
  if (attrs && [attrs fileSize] > kMaxLogBytes) {
    [fm removeItemAtPath:LogPath() error:nil];
  }
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

// i2pd exits the process on an unknown option, so every key here is one that
// exists in this pinned i2pd version.
static NSString* WriteConfig(void) {
  NSMutableString* s = [NSMutableString string];
  [s appendString:@"# generated by ios2pd - rewritten on every connect\n"];
  [s appendString:@"log = file\n"];
  [s appendFormat:@"logfile = %@\n", LogPath()];
  [s appendString:@"loglevel = info\n"];
  // A VPN extension has a much smaller memory budget than an app, so this
  // router is a pure client: it never relays other people's traffic.
  [s appendString:@"notransit = true\n"];
  [s appendString:@"bandwidth = L\n"];
  [s appendString:@"\n[limits]\ntransittunnels = 0\n"];
  [s appendString:@"\n[precomputation]\nelgamal = false\n"];
  [s appendFormat:@"\n[httpproxy]\nenabled = true\naddress = 127.0.0.1\nport = %d\n",
                  kHttpProxyPort];
  [s appendString:@"\n[socksproxy]\nenabled = false\n"];
  [s appendString:@"\n[sam]\nenabled = false\n"];
  [s appendString:@"\n[i2cp]\nenabled = false\n"];
  [s appendString:@"\n[http]\nenabled = false\n"];
  [s appendString:@"\n[upnp]\nenabled = false\n"];
  [s appendString:@"\n[reseed]\nverify = true\n"];

  NSString* path = [DataDir() stringByAppendingPathComponent:@"i2pd.conf"];
  [s writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:nil];
  return path;
}

// ---------------------------------------------------------------------------
// Daemon
// ---------------------------------------------------------------------------

namespace {

std::atomic<bool> gRunning{false};
std::atomic<bool> gStatsStop{false};
std::thread gDaemonThread;
std::thread gStatsThread;

NSString* RouterStatusString() {
  switch (i2p::context.GetStatus()) {
    case i2p::eRouterStatusOK: return @"OK";
    case i2p::eRouterStatusFirewalled: return @"Firewalled";
    case i2p::eRouterStatusUnknown: return @"Testing";
    case i2p::eRouterStatusProxy: return @"Proxy";
    case i2p::eRouterStatusMesh: return @"Mesh";
    case i2p::eRouterStatusStan: return @"Stan";
  }
  return @"—";
}

void WriteStatus() {
  @autoreleasepool {
    NSDictionary* status = @{
      @"uptime" : @((NSInteger)i2p::context.GetUptime()),
      @"inbound" : @((NSInteger)i2p::tunnel::tunnels.CountInboundTunnels()),
      @"outbound" : @((NSInteger)i2p::tunnel::tunnels.CountOutboundTunnels()),
      @"routers" : @((NSInteger)i2p::data::netdb.GetNumRouters()),
      @"status" : RouterStatusString(),
    };
    [status writeToURL:StatusURL() error:nil];
  }
}

bool StartDaemon() {
  if (gRunning.load()) return true;

  TrimLog();
  std::string conf = WriteConfig().UTF8String;
  std::string datadir = DataDir().UTF8String;

  // The reseed SU3 signing certificates ship read-only inside this appex.
  // Without them signature verification fails and the router never bootstraps.
  NSString* certs =
      [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"certificates"];

  std::vector<std::string> args = {
      "ios2pd",
      "--datadir=" + datadir,
      "--certsdir=" + std::string(certs.UTF8String),
      "--conf=" + conf,
  };
  std::vector<char*> argv;
  argv.reserve(args.size());
  for (auto& arg : args) argv.push_back(&arg[0]);

  if (!Daemon.init(static_cast<int>(argv.size()), argv.data())) return false;
  if (!Daemon.start()) return false;

  gRunning.store(true);
  gDaemonThread = std::thread([] { Daemon.run(); });

  gStatsStop.store(false);
  gStatsThread = std::thread([] {
    while (!gStatsStop.load()) {
      if (gRunning.load()) WriteStatus();
      std::this_thread::sleep_for(std::chrono::seconds(2));
    }
  });
  return true;
}

void StopDaemon() {
  if (!gRunning.load()) return;

  gStatsStop.store(true);
  if (gStatsThread.joinable()) gStatsThread.join();

  Daemon.running = false;
  if (gDaemonThread.joinable()) gDaemonThread.join();
  Daemon.stop();
  gRunning.store(false);
}

}  // namespace

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

@implementation PacketTunnelProvider

- (void)startTunnelWithOptions:(NSDictionary<NSString*, NSObject*>*)options
             completionHandler:(void (^)(NSError* _Nullable))completionHandler {
  // Reseeding can take a moment; keep it off the extension's main queue.
  dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
    OPENSSL_init_ssl(0, NULL);

    if (!StartDaemon()) {
      completionHandler([NSError
          errorWithDomain:@"ios2pd"
                     code:1
                 userInfo:@{
                   NSLocalizedDescriptionKey :
                       @"i2pd could not start. Check the Logs tab for details."
                 }]);
      return;
    }

    // Proxy-only tunnel: no routes are included, so no packets are handed to
    // this extension. All it does is tell the system to send *.i2p through the
    // router's HTTP proxy on loopback.
    NEPacketTunnelNetworkSettings* settings = [[NEPacketTunnelNetworkSettings alloc]
        initWithTunnelRemoteAddress:@"198.18.0.1"];

    NEIPv4Settings* ipv4 =
        [[NEIPv4Settings alloc] initWithAddresses:@[ @"198.18.0.2" ]
                                      subnetMasks:@[ @"255.255.255.255" ]];
    ipv4.includedRoutes = @[];
    settings.IPv4Settings = ipv4;

    NEProxyServer* proxy = [[NEProxyServer alloc] initWithAddress:@"127.0.0.1"
                                                             port:kHttpProxyPort];
    NEProxySettings* proxySettings = [[NEProxySettings alloc] init];
    proxySettings.HTTPEnabled = YES;
    proxySettings.HTTPServer = proxy;
    proxySettings.HTTPSEnabled = YES;
    proxySettings.HTTPSServer = proxy;
    proxySettings.excludeSimpleHostnames = YES;
    proxySettings.matchDomains = @[ @"i2p" ];
    settings.proxySettings = proxySettings;

    [self setTunnelNetworkSettings:settings
                 completionHandler:^(NSError* _Nullable error) {
                   completionHandler(error);
                 }];
  });
}

- (void)stopTunnelWithReason:(NEProviderStopReason)reason
           completionHandler:(void (^)(void))completionHandler {
  StopDaemon();
  completionHandler();
}

@end
