//  PacketTunnelProvider.mm — runs the i2pd daemon inside the VPN extension and
//  points the system at its local HTTP proxy for *.i2p.
//
//  Everything lives in the extension's own container and reaches the app over
//  handleAppMessage. There is deliberately no app group: a sideloaded build is
//  signed against a profile that will not have one registered, and claiming an
//  entitlement the profile does not grant stops the extension from launching.

// Apple's AssertMacros.h defines a bare `check` macro that collides with the
// Boost headers the i2pd includes pull in. Opt out of the un-underscored names.
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0

#import "PacketTunnelProvider.h"

#import <Foundation/Foundation.h>

#include <atomic>
#include <string>
#include <thread>
#include <vector>

#include <openssl/ssl.h>

#include "Daemon.h"
#include "NetDb.hpp"
#include "RouterContext.h"
#include "Tunnel.h"

static const int kHttpProxyPort = 4444;
static const unsigned long long kMaxLogBytes = 1024 * 1024;
static const unsigned long long kLogTailBytes = 64 * 1024;

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

static NSString* DataDir(void) {
  NSString* dir = [NSHomeDirectory() stringByAppendingPathComponent:@"i2pd"];
  [[NSFileManager defaultManager] createDirectoryAtPath:dir
                           withIntermediateDirectories:YES
                                            attributes:nil
                                                 error:nil];
  return dir;
}

static NSString* LogPath(void) {
  return [NSHomeDirectory() stringByAppendingPathComponent:@"i2pd.log"];
}

// i2pd appends to its logfile forever, so drop it once it gets large.
// ponytail: truncate-on-connect, not real rotation. Only worth replacing if a
// single session ever needs more than kMaxLogBytes of history.
static void TrimLog(void) {
  NSFileManager* fm = [NSFileManager defaultManager];
  NSDictionary* attrs = [fm attributesOfItemAtPath:LogPath() error:nil];
  if (attrs && [attrs fileSize] > kMaxLogBytes) {
    [fm removeItemAtPath:LogPath() error:nil];
  }
}

static NSString* LogTail(void) {
  NSFileHandle* fh = [NSFileHandle fileHandleForReadingAtPath:LogPath()];
  if (!fh) return @"";
  unsigned long long end = [fh seekToEndOfFile];
  [fh seekToFileOffset:end > kLogTailBytes ? end - kLogTailBytes : 0];
  NSData* data = [fh readDataToEndOfFile];
  [fh closeFile];
  NSString* text = [[NSString alloc] initWithData:data
                                         encoding:NSUTF8StringEncoding];
  // The tail can start mid-sequence; Latin-1 never fails to decode.
  return text ?: [[NSString alloc] initWithData:data
                                       encoding:NSISOLatin1StringEncoding]
                     ?: @"";
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

// i2pd exits the process on an unknown option, so every key here is one that
// exists in this pinned i2pd version.
static NSString* WriteConfig(void) {
  NSMutableString* s = [NSMutableString string];
  [s appendString:@"# generated by ios2pd - rewritten on every connect\n"];
  [s appendString:@"log = file\n"];
  [s appendFormat:@"logfile = %@\n", LogPath()];
  [s appendString:@"loglevel = info\n"];
  // A VPN extension has a much smaller memory budget than an app, so this
  // router is a pure client: it never relays other people's traffic.
  [s appendString:@"notransit = true\n"];
  [s appendString:@"bandwidth = L\n"];
  [s appendString:@"\n[limits]\ntransittunnels = 0\n"];
  [s appendString:@"\n[precomputation]\nelgamal = false\n"];
  [s appendFormat:@"\n[httpproxy]\nenabled = true\naddress = 127.0.0.1\nport = %d\n",
                  kHttpProxyPort];
  [s appendString:@"\n[socksproxy]\nenabled = false\n"];
  [s appendString:@"\n[sam]\nenabled = false\n"];
  [s appendString:@"\n[http]\nenabled = false\n"];
  [s appendString:@"\n[reseed]\nverify = true\n"];

  NSString* path = [DataDir() stringByAppendingPathComponent:@"i2pd.conf"];
  [s writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:nil];
  return path;
}

// ---------------------------------------------------------------------------
// Daemon
// ---------------------------------------------------------------------------

namespace {

std::atomic<bool> gRunning{false};
std::thread gDaemonThread;

NSString* RouterStatusString() {
  switch (i2p::context.GetStatus()) {
    case i2p::eRouterStatusOK: return @"OK";
    case i2p::eRouterStatusFirewalled: return @"Firewalled";
    case i2p::eRouterStatusUnknown: return @"Testing";
    case i2p::eRouterStatusProxy: return @"Proxy";
    case i2p::eRouterStatusMesh: return @"Mesh";
    case i2p::eRouterStatusStan: return @"Stan";
  }
  return @"—";
}

bool StartDaemon() {
  if (gRunning.load()) return true;

  TrimLog();
  std::string conf = WriteConfig().UTF8String;
  std::string datadir = DataDir().UTF8String;

  // The reseed SU3 signing certificates ship read-only inside this appex.
  // Without them signature verification fails and the router never bootstraps.
  NSString* certs =
      [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"certificates"];

  std::vector<std::string> args = {
      "ios2pd",
      "--datadir=" + datadir,
      "--certsdir=" + std::string(certs.UTF8String),
      "--conf=" + conf,
  };
  std::vector<char*> argv;
  argv.reserve(args.size());
  for (auto& arg : args) argv.push_back(&arg[0]);

  // These land in the device console. They are the only trace left if i2pd
  // exits before it opens its own logfile.
  NSLog(@"[ios2pd] datadir=%s certsdir=%s", datadir.c_str(), certs.UTF8String);
  if (!Daemon.init(static_cast<int>(argv.size()), argv.data())) {
    NSLog(@"[ios2pd] Daemon.init failed");
    return false;
  }
  NSLog(@"[ios2pd] Daemon.init ok");
  if (!Daemon.start()) {
    NSLog(@"[ios2pd] Daemon.start failed");
    return false;
  }
  NSLog(@"[ios2pd] Daemon.start ok");

  gRunning.store(true);
  gDaemonThread = std::thread([] { Daemon.run(); });
  return true;
}

void StopDaemon() {
  if (!gRunning.load()) return;
  Daemon.running = false;
  if (gDaemonThread.joinable()) gDaemonThread.join();
  Daemon.stop();
  gRunning.store(false);
}

}  // namespace

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

@implementation PacketTunnelProvider

- (void)startTunnelWithOptions:(NSDictionary<NSString*, NSObject*>*)options
             completionHandler:(void (^)(NSError* _Nullable))completionHandler {
  NSLog(@"[ios2pd] startTunnel entered");

  // Proxy-only tunnel: no routes are included, so no packets are handed to
  // this extension. All it does is tell the system to send *.i2p through the
  // router's HTTP proxy on loopback.
  NEPacketTunnelNetworkSettings* settings = [[NEPacketTunnelNetworkSettings alloc]
      initWithTunnelRemoteAddress:@"198.18.0.1"];

  NEIPv4Settings* ipv4 =
      [[NEIPv4Settings alloc] initWithAddresses:@[ @"198.18.0.2" ]
                                    subnetMasks:@[ @"255.255.255.255" ]];
  ipv4.includedRoutes = @[];
  settings.IPv4Settings = ipv4;

  NEProxyServer* proxy = [[NEProxyServer alloc] initWithAddress:@"127.0.0.1"
                                                           port:kHttpProxyPort];
  NEProxySettings* proxySettings = [[NEProxySettings alloc] init];
  proxySettings.HTTPEnabled = YES;
  proxySettings.HTTPServer = proxy;
  proxySettings.HTTPSEnabled = YES;
  proxySettings.HTTPSServer = proxy;
  proxySettings.excludeSimpleHostnames = YES;
  proxySettings.matchDomains = @[ @"i2p" ];
  settings.proxySettings = proxySettings;

  // Bring the tunnel up before starting the router. Reseeding can take a while
  // and iOS kills a tunnel whose start handler has not returned in 60s, so the
  // daemon runs after the handshake and cancels the tunnel if it fails.
  [self setTunnelNetworkSettings:settings
               completionHandler:^(NSError* _Nullable error) {
                 NSLog(@"[ios2pd] setTunnelNetworkSettings: %@", error ?: @"ok");
                 completionHandler(error);
                 if (error) return;
                 dispatch_async(
                     dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
                       OPENSSL_init_ssl(0, NULL);
                       if (StartDaemon()) return;
                       [self cancelTunnelWithError:
                                 [NSError errorWithDomain:@"ios2pd"
                                                     code:1
                                                 userInfo:@{
                                                   NSLocalizedDescriptionKey :
                                                       @"i2pd failed to start"
                                                 }]];
                     });
               }];
}

- (void)stopTunnelWithReason:(NEProviderStopReason)reason
           completionHandler:(void (^)(void))completionHandler {
  StopDaemon();
  completionHandler();
}

// The app polls this for the log tail and router stats; it is the only channel
// between the two processes.
- (void)handleAppMessage:(NSData*)messageData
       completionHandler:(void (^)(NSData* _Nullable))completionHandler {
  if (!completionHandler) return;
  @autoreleasepool {
    BOOL up = gRunning.load();
    NSDictionary* payload = @{
      @"running" : @(up),
      @"log" : LogTail(),
      @"uptime" : @(up ? (NSInteger)i2p::context.GetUptime() : 0),
      @"inbound" : @(up ? (NSInteger)i2p::tunnel::tunnels.CountInboundTunnels() : 0),
      @"outbound" : @(up ? (NSInteger)i2p::tunnel::tunnels.CountOutboundTunnels() : 0),
      @"routers" : @(up ? (NSInteger)i2p::data::netdb.GetNumRouters() : 0),
      @"status" : up ? RouterStatusString() : @"—",
    };
    completionHandler([NSJSONSerialization dataWithJSONObject:payload
                                                      options:0
                                                        error:nil]);
  }
}

@end
