//  I2pdCore.mm — i2pd (I2P daemon) core bridge for the ios2pd SwiftUI app.
//
//  Links the i2pd C++ daemon core (DaemonUnix) into the app. The router runs
//  on a background thread; logs are captured through a custom std::ostream and
//  surfaced to the UI.
//
//  The daemon is configured from two INI files this file writes into
//  <Documents>/i2pd:
//    i2pd.conf     - basic settings + the user's custom.conf block (appended).
//    tunnels.conf  - client/server tunnels edited in the Tunnels tab.
//  Both are passed via --conf / --tunconf on start.
//
//  Also owns the backloop.dev integration: refresh the loopback SSL
//  certificate, run the local HTTPS server that serves /install.mobileconfig
//  and relays everything else to the i2pd web console (:7070), plus the
//  i2p-http/i2p-https WKURLSchemeHandler used by the in-app browser.

#import "I2pdCore.h"

#import <Foundation/Foundation.h>
#import <AVFoundation/AVFoundation.h>
#import <NetworkExtension/NetworkExtension.h>
#import <SystemConfiguration/CaptiveNetwork.h>
#import <WebKit/WebKit.h>

#include <atomic>
#include <cctype>
#include <cstdlib>
#include <mutex>
#include <ostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <poll.h>
#include <unistd.h>
#include <cstring>

#include <openssl/ssl.h>
#include <openssl/err.h>

#include "Daemon.h"
#include "Log.h"
#include "Config.h"
#include "FS.h"

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------
static NSUserDefaults* UD() { return [NSUserDefaults standardUserDefaults]; }
static BOOL SettingBool(NSString* key, BOOL def) {
  id v = [UD() objectForKey:key];
  return v ? [v boolValue] : def;
}
static int SettingInt(NSString* key, int def) {
  id v = [UD() objectForKey:key];
  return v ? [v intValue] : def;
}
static NSString* SettingString(NSString* key, NSString* def) {
  NSString* v = [UD() stringForKey:key];
  return (v && v.length) ? v : def;
}

static NSString* const kHttpOn = @"i2pd_http_enabled";
static NSString* const kHttpPort = @"i2pd_http_port";
static NSString* const kSocksOn = @"i2pd_socks_enabled";
static NSString* const kSocksPort = @"i2pd_socks_port";
static NSString* const kSamOn = @"i2pd_sam_enabled";
static NSString* const kSamPort = @"i2pd_sam_port";
static NSString* const kLogLevel = @"i2pd_loglevel";
static NSString* const kBackloopHost = @"backloop_host";
static NSString* const kBackloopPort = @"backloop_https_port";
static NSString* const kKeepAlive = @"keepalive_audio";
static NSString* const kSslNotAfter = @"backloop_notafter";
static NSString* const kSsid = @"backloop_ssid";
static NSString* const kConsolePort = @"i2pd_webconsole_port";
static NSString* const kTunnels = @"tunnels";

// ---------------------------------------------------------------------------
// Config files (i2pd.conf + tunnels.conf) in <Documents>/i2pd
// ---------------------------------------------------------------------------
static NSString* ConfDir(void) {
  NSString* docs = [NSSearchPathForDirectoriesInDomains(
      NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
  return [docs stringByAppendingPathComponent:@"i2pd"];
}
static NSString* ConfPath(void) {
  return [ConfDir() stringByAppendingPathComponent:@"i2pd.conf"];
}
static NSString* TunnelsPath(void) {
  return [ConfDir() stringByAppendingPathComponent:@"tunnels.conf"];
}
static NSString* CustomConfPath(void) {
  return [ConfDir() stringByAppendingPathComponent:@"custom.conf"];
}

static BOOL EnsureConfDir(void) {
  NSFileManager* fm = [NSFileManager defaultManager];
  return [fm fileExistsAtPath:ConfDir()] ||
         [fm createDirectoryAtPath:ConfDir() withIntermediateDirectories:YES
                         attributes:nil error:nil];
}

// Persists the tunnels list (array of dicts) to NSUserDefaults.
static NSMutableArray* TunnelsList(void) {
  NSArray* stored = [UD() arrayForKey:kTunnels];
  return stored ? [stored mutableCopy] : [NSMutableArray array];
}
static void SaveTunnels(NSArray* list) {
  [UD() setObject:list forKey:kTunnels];
}

// Writes i2pd.conf from the UI settings + the user's custom.conf block.
static void WriteConfFile(void) {
  EnsureConfDir();
  NSMutableString* s = [NSMutableString string];
  [s appendString:@"# generated by ios2pd - edit via the app\n"];
  [s appendString:@"log = stdout\n"];
  [s appendFormat:@"loglevel = %@\n", SettingString(kLogLevel, @"info")];
  [s appendString:@"\n[httpproxy]\n"];
  [s appendFormat:@"enabled = %@\n", SettingBool(kHttpOn, YES) ? @"true" : @"false"];
  [s appendFormat:@"port = %d\n", SettingInt(kHttpPort, 4444)];
  [s appendString:@"\n[socksproxy]\n"];
  [s appendFormat:@"enabled = %@\n", SettingBool(kSocksOn, YES) ? @"true" : @"false"];
  [s appendFormat:@"port = %d\n", SettingInt(kSocksPort, 4447)];
  [s appendString:@"\n[sam]\n"];
  [s appendFormat:@"enabled = %@\n", SettingBool(kSamOn, YES) ? @"true" : @"false"];
  [s appendFormat:@"port = %d\n", SettingInt(kSamPort, 7656)];
  NSString* custom =
      [NSString stringWithContentsOfFile:CustomConfPath()
                                encoding:NSUTF8StringEncoding error:nil];
  if (custom.length) {
    [s appendString:@"\n# ---- user custom config ----\n"];
    [s appendString:custom];
    if (![custom hasSuffix:@"\n"]) [s appendString:@"\n"];
  }
  [s writeToFile:ConfPath() atomically:YES encoding:NSUTF8StringEncoding
           error:nil];
}

static void WriteTunnelsFile(void) {
  NSArray* tunnels = TunnelsList();
  if (!tunnels.count) return;
  EnsureConfDir();
  NSMutableString* s = [NSMutableString string];
  [s appendString:@"# tunnels configured in the ios2pd app\n"];
  for (NSDictionary* t in tunnels) {
    NSString* name = t[@"name"];
    if (!name.length) continue;
    NSString* type = t[@"type"] ?: @"client";
    [s appendFormat:@"\n[%@]\n", name];
    [s appendFormat:@"type = %@\n", type];
    if ([type isEqualToString:@"client"] || [type isEqualToString:@"socks"]) {
      [s appendFormat:@"address = %@\n", t[@"address"] ?: @"127.0.0.1"];
    }
    [s appendFormat:@"port = %@\n", t[@"port"] ?: @"0"];
    if ([type isEqualToString:@"client"]) {
      [s appendFormat:@"destination = %@\n", t[@"destination"] ?: @""];
      if ([t[@"keys"] length]) [s appendFormat:@"keys = %@\n", t[@"keys"]];
      if ([t[@"destinationport"] length])
        [s appendFormat:@"destinationport = %@\n", t[@"destinationport"]];
    } else if ([type isEqualToString:@"server"] ||
               [type isEqualToString:@"http"]) {
      [s appendFormat:@"host = %@\n", t[@"host"] ?: @"127.0.0.1"];
      if ([t[@"keys"] length]) [s appendFormat:@"keys = %@\n", t[@"keys"]];
      if ([t[@"inport"] length]) [s appendFormat:@"inport = %@\n", t[@"inport"]];
    } else if ([type isEqualToString:@"socks"]) {
      if ([t[@"keys"] length]) [s appendFormat:@"keys = %@\n", t[@"keys"]];
    }
  }
  [s writeToFile:TunnelsPath() atomically:YES encoding:NSUTF8StringEncoding
           error:nil];
}

// Best-effort read of the current Wi-Fi SSID. Returns nil if unavailable (the
// user types it).
static NSString* CurrentSSID(void) {
  NSArray* ifs = (__bridge_transfer NSArray*)CNCopySupportedInterfaces();
  for (NSString* ifname in ifs) {
    NSDictionary* info = (__bridge_transfer NSDictionary*)
        CNCopyCurrentNetworkInfo((__bridge CFStringRef)ifname);
    NSString* ssid = info[(__bridge NSString*)kCNNetworkInfoKeySSID];
    if (ssid.length) return ssid;
  }
  return nil;
}

// ---------------------------------------------------------------------------
// Daemon bridge
// ---------------------------------------------------------------------------
namespace {

std::mutex gLogMutex;
std::string gLog;
std::atomic<bool> gStarted{false};
std::thread gDaemonThread;

// A streambuf that appends every byte written by i2pd's logger into gLog.
struct IosLogBuf : std::streambuf {
  int overflow(int c) override {
    if (c != EOF) {
      std::lock_guard<std::mutex> lock(gLogMutex);
      gLog.push_back(static_cast<char>(c));
      if (gLog.size() > (256 * 1024)) {
        gLog.erase(0, gLog.size() - (256 * 1024));
      }
    }
    return c;
  }
};

bool StartDaemon() {
  if (gStarted.load()) return true;

  WriteConfFile();
  WriteTunnelsFile();
  if (!EnsureConfDir()) return false;

  std::string datadir = std::string(ConfDir().UTF8String);
  std::vector<std::string> args = {
      "ios2pd",
      "--datadir=" + datadir,
      "--conf=" + std::string(ConfPath().UTF8String),
      "--log=stdout",
  };
  if (TunnelsList().count) {
    args.push_back("--tunconf=" + std::string(TunnelsPath().UTF8String));
  }

  std::vector<char*> argv;
  argv.reserve(args.size());
  for (auto& a : args) argv.push_back(&a[0]);

  static IosLogBuf logBuf;
  static std::ostream logStream(&logBuf);
  std::shared_ptr<std::ostream> sink(&logStream, [](std::ostream*) {});

  if (!Daemon.init(static_cast<int>(argv.size()), argv.data(), sink)) {
    return false;
  }
  if (!Daemon.start()) {
    return false;
  }
  gStarted.store(true);
  gDaemonThread = std::thread([]() { Daemon.run(); });
  return true;
}

void StopDaemon() {
  if (!gStarted.load()) return;
  Daemon.running = false;
  if (gDaemonThread.joinable()) gDaemonThread.join();
  Daemon.stop();
  gStarted.store(false);
}

std::string TakeLog() {
  std::lock_guard<std::mutex> lock(gLogMutex);
  return gLog;
}

// Installs (or updates) the NEAppProxyProvider VPN profile that routes *.i2p
// traffic through the local i2pd SOCKS proxy. Requires the
// com.apple.developer.networking.networkextension entitlement at signing time;
// without it this is a harmless no-op.
void InstallVpnProfile() {
  NEAppProxyProviderManager* mgr =
      (NEAppProxyProviderManager*)[NEAppProxyProviderManager sharedManager];
  [mgr loadFromPreferencesWithCompletionHandler:^(NSError* _Nullable err) {
    NETunnelProviderProtocol* proto = [[NETunnelProviderProtocol alloc] init];
    proto.providerBundleIdentifier = @"org.nouvborne.ios2pd.appproxy";
    proto.serverAddress = @"i2pd";
    proto.providerConfiguration = @{
      @"proxyHost" : @"127.0.0.1",
      @"proxyPort" : @(SettingInt(kSocksPort, 4447)),
    };
    mgr.protocolConfiguration = proto;
    mgr.localizedDescription = @"ios2pd I2P VPN";
    mgr.enabled = YES;
    [mgr saveToPreferencesWithCompletionHandler:^(NSError* _Nullable saveErr) {
      if (saveErr) {
        NSLog(@"[ios2pd] VPN profile save failed: %@", saveErr);
      }
    }];
  }];
}

NSString* VpnStatusString() {
  NEVPNConnection* conn = [NEAppProxyProviderManager sharedManager].connection;
  switch (conn.status) {
    case NEVPNStatusInvalid:
      return @"not configured";
    case NEVPNStatusDisconnected:
      return @"Disconnected";
    case NEVPNStatusConnecting:
      return @"Connecting";
    case NEVPNStatusConnected:
      return @"Connected";
    case NEVPNStatusReasserting:
      return @"Reconnecting";
    case NEVPNStatusDisconnecting:
      return @"Disconnecting";
  }
  return @"?";
}

}  // namespace

// ---------------------------------------------------------------------------
// Background keep-alive (silent audio so the proxy stays up in Safari)
// ---------------------------------------------------------------------------
@interface KeepAlive : NSObject
+ (instancetype)shared;
- (void)apply;
@end

@implementation KeepAlive {
  AVAudioPlayer* _player;
}

+ (instancetype)shared {
  static KeepAlive* instance;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    instance = [[KeepAlive alloc] init];
  });
  return instance;
}

// 1 second of 8 kHz mono 16-bit PCM silence as a WAV.
+ (NSData*)silentWavData {
  const int sr = 8000, ch = 1, bits = 16;
  const int samples = sr * 1;
  const int dataSize = samples * (bits / 8);
  NSMutableData* d = [NSMutableData dataWithCapacity:44 + dataSize];
  uint8_t hdr[44] = {0};
  hdr[0] = 'R'; hdr[1] = 'I'; hdr[2] = 'F'; hdr[3] = 'F';
  uint32_t u = 36 + dataSize; memcpy(hdr + 4, &u, 4);
  hdr[8] = 'W'; hdr[9] = 'A'; hdr[10] = 'V'; hdr[11] = 'E';
  hdr[12] = 'f'; hdr[13] = 'm'; hdr[14] = 't'; hdr[15] = ' ';
  u = 16; memcpy(hdr + 16, &u, 4);
  uint16_t s = 1; memcpy(hdr + 20, &s, 2);
  s = ch; memcpy(hdr + 22, &s, 2);
  u = sr; memcpy(hdr + 24, &u, 4);
  u = sr * ch * (bits / 8); memcpy(hdr + 28, &u, 4);
  s = ch * (bits / 8); memcpy(hdr + 32, &s, 2);
  s = bits; memcpy(hdr + 34, &s, 2);
  hdr[36] = 'd'; hdr[37] = 'a'; hdr[38] = 't'; hdr[39] = 'a';
  u = dataSize; memcpy(hdr + 40, &u, 4);
  [d appendBytes:hdr length:44];
  [d increaseLengthBy:dataSize];
  return d;
}

- (void)apply {
  BOOL on = SettingBool(kKeepAlive, NO);
  AVAudioSession* session = [AVAudioSession sharedInstance];
  if (on) {
    [session setCategory:AVAudioSessionCategoryPlayback error:nil];
    [session setActive:YES error:nil];
    if (!_player) {
      NSData* wav = [[self class] silentWavData];
      NSString* path = [NSTemporaryDirectory() stringByAppendingPathComponent:@"ios2pd-silence.wav"];
      [wav writeToFile:path atomically:YES];
      _player = [[AVAudioPlayer alloc] initWithContentsOfURL:[NSURL fileURLWithPath:path] error:nil];
      _player.numberOfLoops = -1;
      _player.volume = 0.0f;
      [_player prepareToPlay];
    }
    [_player play];
  } else {
    [_player stop];
    _player = nil;
    [session setActive:NO
           withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation
                 error:nil];
  }
}

@end

// ---------------------------------------------------------------------------
// backloop.dev SSL certificate + local HTTPS server
// ---------------------------------------------------------------------------
static NSString* SslDirPath(void) {
  NSString* docs = [NSSearchPathForDirectoriesInDomains(
      NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
  return [docs stringByAppendingPathComponent:@"backloop"];
}

static BOOL SslHasCert(void) {
  NSFileManager* fm = [NSFileManager defaultManager];
  NSString* dir = SslDirPath();
  return [fm fileExistsAtPath:[dir stringByAppendingPathComponent:@"cert.pem"]] &&
         [fm fileExistsAtPath:[dir stringByAppendingPathComponent:@"key.pem"]];
}

// Downloads the current *.backloop.dev wildcard cert/key from backloop.dev and
// stores them (cert+CA chain and key1+key2 concatenated) for the local HTTPS
// server. The cert is intentionally public - it only secures loopback.
static BOOL SslRefresh(NSError** error) {
  NSURL* url = [NSURL URLWithString:@"https://backloop.dev/pack.json"];
  NSData* data = [NSData dataWithContentsOfURL:url
                                       options:NSDataReadingUncached
                                         error:error];
  if (!data) return NO;
  NSError* jsonErr = nil;
  id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:&jsonErr];
  if (!parsed || ![parsed isKindOfClass:[NSDictionary class]]) {
    if (error) *error = jsonErr ?: [NSError errorWithDomain:@"ios2pd" code:1
        userInfo:@{NSLocalizedDescriptionKey : @"pack.json was not an object"}];
    return NO;
  }
  NSDictionary* pack = (NSDictionary*)parsed;
  NSString* cert = pack[@"cert"];
  NSString* ca = pack[@"ca"];
  NSString* k1 = pack[@"key1"];
  NSString* k2 = pack[@"key2"];
  if (!cert.length || !k1.length || !k2.length) {
    if (error) *error = [NSError errorWithDomain:@"ios2pd" code:2
        userInfo:@{NSLocalizedDescriptionKey : @"pack.json is missing cert/key fields"}];
    return NO;
  }
  NSString* bundle = ca.length ? [NSString stringWithFormat:@"%@\n%@", cert, ca]
                               : cert;
  NSString* key = [k1 stringByAppendingString:k2];
  NSFileManager* fm = [NSFileManager defaultManager];
  NSString* dir = SslDirPath();
  [fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];
  NSError* writeErr = nil;
  BOOL ok = [bundle writeToFile:[dir stringByAppendingPathComponent:@"cert.pem"]
                     atomically:YES encoding:NSUTF8StringEncoding error:&writeErr];
  ok = ok && [key writeToFile:[dir stringByAppendingPathComponent:@"key.pem"]
                  atomically:YES encoding:NSUTF8StringEncoding error:&writeErr];
  NSDictionary* info = pack[@"info"];
  if ([info isKindOfClass:[NSDictionary class]] && info[@"notAfter"]) {
    [UD() setObject:info[@"notAfter"] forKey:kSslNotAfter];
  }
  if (!ok && error) *error = writeErr;
  return ok;
}

static NSString* SslNotAfterString(void) {
  NSString* v = [UD() stringForKey:kSslNotAfter];
  if (!v.length) return @"not installed";
  NSDateFormatter* f = [[NSDateFormatter alloc] init];
  f.locale = [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"];
  f.dateFormat = @"yyyy-MM-dd'T'HH:mm:ss'Z'";
  f.timeZone = [NSTimeZone timeZoneForSecondsFromGMT:0];
  NSDate* d = [f dateFromString:v];
  if (!d) return v;
  NSDateFormatter* out = [[NSDateFormatter alloc] init];
  out.dateStyle = NSDateFormatterMediumStyle;
  out.timeStyle = NSDateFormatterShortStyle;
  return [out stringFromDate:d];
}

// Builds the Wi-Fi managed payload profile that points the HTTP proxy at the
// device's own loopback via a *.backloop.dev hostname. iOS requires SSID_STR
// for com.apple.wifi.managed, so the profile is keyed to the Wi-Fi network
// the user entered.
static NSData* MobileConfigData(void) {
  NSString* host = SettingString(kBackloopHost, @"ios2pd.backloop.dev");
  int port = SettingInt(kHttpPort, 4444);
  NSString* ssid = SettingString(kSsid, @"");
  NSMutableDictionary* wifi = [NSMutableDictionary dictionary];
  wifi[@"PayloadType"] = @"com.apple.wifi.managed";
  wifi[@"PayloadVersion"] = @1;
  wifi[@"PayloadIdentifier"] = @"org.nouvborne.ios2pd.proxy.wifi";
  wifi[@"PayloadUUID"] = [NSUUID UUID].UUIDString;
  wifi[@"PayloadDisplayName"] = @"ios2pd I2P HTTP proxy";
  if (ssid.length) wifi[@"SSID_STR"] = ssid;
  wifi[@"ProxyType"] = @"Manual";
  wifi[@"ProxyServer"] = host;
  wifi[@"ProxyServerPort"] = @(port);

  NSMutableDictionary* profile = [NSMutableDictionary dictionary];
  profile[@"PayloadType"] = @"Configuration";
  profile[@"PayloadVersion"] = @1;
  profile[@"PayloadIdentifier"] = @"org.nouvborne.ios2pd.proxy";
  profile[@"PayloadUUID"] = [NSUUID UUID].UUIDString;
  profile[@"PayloadDisplayName"] = @"ios2pd I2P Proxy (backloop.dev)";
  profile[@"PayloadDescription"] =
      [NSString stringWithFormat:
          @"Sets the Wi-Fi HTTP proxy to %@:%d (resolves to this device's "
          @"loopback) so HTTP/HTTPS traffic is routed through the local i2pd "
          @"daemon running in the ios2pd app. Applies while connected to "
          @"\"%@\".",
          host, port, ssid.length ? ssid : @"your Wi-Fi"];
  profile[@"PayloadContent"] = @[ wifi ];
  return [NSPropertyListSerialization dataWithPropertyList:profile
                                                    format:NSPropertyListXMLFormat_v1_0
                                                   options:0
                                                     error:nil] ?: [NSData data];
}

static NSData* HomeHtmlData(void) {
  NSString* host = SettingString(kBackloopHost, @"ios2pd.backloop.dev");
  int port = SettingInt(kHttpPort, 4444);
  NSString* html = [NSString stringWithFormat:
      @"<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" "
      @"content=\"width=device-width\"><title>ios2pd</title></head><body>"
      @"<h2>ios2pd local server</h2>"
      @"<p>This HTTPS server runs on this device (loopback via backloop.dev).</p>"
      @"<p><a href=\"/install.mobileconfig\">Install the I2P proxy profile</a></p>"
      @"<p><a href=\"/\">Open the i2pd web console (port 7070)</a></p>"
      @"<p>Proxy: <code>%@</code>:<code>%d</code></p>"
      @"<p>Start i2pd in the app, then browse <code>*.i2p</code> sites in Safari.</p>"
      @"</body></html>", host, port];
  return [html dataUsingEncoding:NSUTF8StringEncoding];
}

static std::atomic<bool> gSslStop{false};
static std::thread gSslThread;

// Web-console proxy: everything served over the backloop HTTPS server except
// /install.mobileconfig and /home is relayed to the i2pd web console on
// 127.0.0.1:<console port>, so the panel is reachable in-app or in Safari at
// https://<host>:<port>/ with a publicly trusted certificate.

struct PanelReq {
  std::string method;
  std::string target;
  std::string body;
  std::vector<std::pair<std::string, std::string>> headers;
};

static std::string Lower(std::string s) {
  for (size_t i = 0; i < s.size(); ++i)
    s[i] = (char)tolower((unsigned char)s[i]);
  return s;
}

static std::string Trim(const std::string& s) {
  size_t a = s.find_first_not_of(" \t\r\n");
  if (a == std::string::npos) return "";
  size_t b = s.find_last_not_of(" \t\r\n");
  return s.substr(a, b - a + 1);
}

// Reads one HTTP/1.x request (request line + headers + body) from the TLS
// connection. Body reads honor Content-Length, capped to stay safe.
static bool ReadHttpRequest(SSL* ssl, PanelReq& req) {
  std::string data;
  char tmp[8192];
  size_t headerEnd = std::string::npos;
  while (headerEnd == std::string::npos) {
    int n = SSL_read(ssl, tmp, sizeof(tmp));
    if (n <= 0) break;
    data.append(tmp, (size_t)n);
    headerEnd = data.find("\r\n\r\n");
    if (data.size() > (256 * 1024)) break;
  }
  if (headerEnd == std::string::npos) return false;
  std::string head = data.substr(0, headerEnd);
  req.body = data.substr(headerEnd + 4);

  size_t eol = head.find("\r\n");
  if (eol == std::string::npos) return false;
  std::istringstream rl(head.substr(0, eol));
  rl >> req.method >> req.target;
  if (req.method.empty() || req.target.empty()) return false;

  int contentLength = -1;
  size_t pos = eol + 2;
  while (pos < head.size()) {
    size_t npos = head.find("\r\n", pos);
    if (npos == std::string::npos) npos = head.size();
    std::string line = head.substr(pos, npos - pos);
    size_t colon = line.find(':');
    if (colon != std::string::npos) {
      req.headers.push_back(
          {Lower(Trim(line.substr(0, colon))), Trim(line.substr(colon + 1))});
      if (req.headers.back().first == "content-length")
        contentLength = atoi(req.headers.back().second.c_str());
    }
    pos = npos + 2;
  }
  if (contentLength > 0) {
    while (req.body.size() < (size_t)contentLength) {
      int n = SSL_read(ssl, tmp, sizeof(tmp));
      if (n <= 0) break;
      req.body.append(tmp, (size_t)n);
      if (req.body.size() > (4 * 1024 * 1024)) break;
    }
  }
  return true;
}

static int ConnectLoopback(int port) {
  int fd = socket(AF_INET, SOCK_STREAM, 0);
  if (fd < 0) return -1;
  struct sockaddr_in a;
  memset(&a, 0, sizeof(a));
  a.sin_family = AF_INET;
  a.sin_port = htons((uint16_t)port);
  a.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  if (connect(fd, (struct sockaddr*)&a, sizeof(a)) != 0) {
    close(fd);
    return -1;
  }
  return fd;
}

// Appends one recv() to data unless it fails or the cap would be exceeded.
static bool RecvSome(int fd, std::string& data, size_t cap) {
  char tmp[16384];
  ssize_t n = recv(fd, tmp, sizeof(tmp), 0);
  if (n <= 0) return false;
  data.append(tmp, (size_t)n);
  return data.size() <= cap;
}

// Reads the full upstream response (headers + body) over a plain socket,
// honoring Content-Length, chunked encoding, or read-until-EOF.
static std::string ReadHttpResponse(int fd) {
  std::string data;
  size_t headerEnd = std::string::npos;
  while (headerEnd == std::string::npos) {
    if (!RecvSome(fd, data, 1024 * 1024)) break;
    headerEnd = data.find("\r\n\r\n");
  }
  if (headerEnd == std::string::npos) return data;

  std::string lowerHead = Lower(data.substr(0, headerEnd));
  bool chunked = lowerHead.find("\r\ntransfer-encoding: chunked") !=
                 std::string::npos;
  int contentLength = -1;
  {
    size_t pos = 0;
    while ((pos = lowerHead.find("\r\ncontent-length:", pos)) !=
           std::string::npos) {
      size_t eol = lowerHead.find("\r\n", pos);
      contentLength =
          atoi(Trim(lowerHead.substr(pos + 17, eol - (pos + 17))).c_str());
      pos = eol;
    }
  }

  if (chunked) {
    while (data.find("\r\n0\r\n") == std::string::npos &&
           data.find("\r\n0\r\n\r\n") == std::string::npos) {
      if (!RecvSome(fd, data, 16 * 1024 * 1024)) break;
    }
  } else if (contentLength >= 0) {
    size_t bodyStart = headerEnd + 4;
    while (data.size() < bodyStart + (size_t)contentLength) {
      if (!RecvSome(fd, data, bodyStart + (size_t)contentLength + 1)) break;
    }
  } else {
    while (RecvSome(fd, data, 16 * 1024 * 1024)) {}
  }
  return data;
}

// Forwards a browser request to the i2pd web console and returns the raw
// upstream response on success.
static bool ForwardToPanel(int port, const PanelReq& req, std::string& out) {
  int fd = ConnectLoopback(port);
  if (fd < 0) return false;
  std::string buf;
  buf += req.method + " " + req.target + " HTTP/1.1\r\n";
  buf += "Host: 127.0.0.1:" + std::to_string(port) + "\r\n";
  for (auto& h : req.headers) {
    const std::string& name = h.first;
    if (name == "host" || name == "connection" || name == "keep-alive" ||
        name == "proxy-connection" || name == "transfer-encoding" ||
        name == "content-length" || name == "upgrade" || name == "te" ||
        name == "trailer" || name == "accept-encoding")
      continue;
    buf += h.first + ": " + h.second + "\r\n";
  }
  if (!req.body.empty())
    buf += "Content-Length: " + std::to_string(req.body.size()) + "\r\n";
  buf += "Connection: close\r\n\r\n";
  buf += req.body;
  size_t sent = 0;
  while (sent < buf.size()) {
    ssize_t w = send(fd, buf.data() + sent, buf.size() - sent, MSG_NOSIGNAL);
    if (w <= 0) break;
    sent += (size_t)w;
  }
  if (sent < buf.size()) {
    close(fd);
    return false;
  }
  out = ReadHttpResponse(fd);
  close(fd);
  return true;
}

static bool PanelHeaderWorthKeeping(const std::string& name) {
  return name == "content-type" || name == "set-cookie" ||
         name == "location" || name == "content-disposition" ||
         name == "cache-control" || name == "expires" || name == "pragma" ||
         name == "content-security-policy" || name == "refresh" ||
         name == "x-frame-options" || name == "x-content-type-options" ||
         name == "content-encoding" || name == "etag" ||
         name == "last-modified" || name == "vary" ||
         name == "www-authenticate" || name == "retry-after" ||
         name == "strict-transport-security";
}

// Rewrites an upstream HTTP response and sends it back over TLS.
static void SendPanelResponse(SSL* ssl, const std::string& raw) {
  size_t headerEnd = raw.find("\r\n\r\n");
  if (headerEnd == std::string::npos) {
    SSL_write(ssl, raw.data(), raw.size());
    return;
  }
  std::string head = raw.substr(0, headerEnd);
  std::string body = raw.substr(headerEnd + 4);
  std::string lowerHead = Lower(head);
  bool chunked =
      lowerHead.find("\r\ntransfer-encoding: chunked") != std::string::npos;

  std::string out;
  size_t eol = head.find("\r\n");
  std::string status =
      (eol == std::string::npos) ? "HTTP/1.1 502 Bad Gateway"
                                 : head.substr(0, eol);
  if (status.find("HTTP/") == std::string::npos)
    status = "HTTP/1.1 502 Bad Gateway";
  out += status + "\r\n";

  size_t pos = (eol == std::string::npos) ? head.size() : eol + 2;
  while (pos < head.size()) {
    size_t npos = head.find("\r\n", pos);
    if (npos == std::string::npos) npos = head.size();
    std::string line = head.substr(pos, npos - pos);
    size_t colon = line.find(':');
    if (colon != std::string::npos &&
        PanelHeaderWorthKeeping(Lower(Trim(line.substr(0, colon)))))
      out += line + "\r\n";
    pos = npos + 2;
  }
  out += "Connection: close\r\n";
  if (chunked) {
    out += "Transfer-Encoding: chunked\r\n";
  } else {
    out += "Content-Length: " + std::to_string(body.size()) + "\r\n";
  }
  out += "\r\n";
  SSL_write(ssl, out.data(), out.size());
  SSL_write(ssl, body.data(), body.size());
}

static std::string PanelErrorResponse(void) {
  std::string body =
      "<!doctype html><html><head><meta charset=\"utf-8\">"
      "<title>ios2pd</title></head><body>"
      "<h2>Web console unreachable</h2>"
      "<p>The i2pd web console is not responding. "
      "Start the router and make sure [http] is enabled in i2pd.conf.</p>"
      "</body></html>";
  return "HTTP/1.1 502 Bad Gateway\r\n"
         "Content-Type: text/html; charset=utf-8\r\n"
         "Content-Length: " +
         std::to_string(body.size()) +
         "\r\n"
         "Connection: close\r\n\r\n" +
         body;
}

// Handles one accepted connection: TLS handshake, then serves
// /install.mobileconfig + /home or proxies everything else to the web console.
static void HandleClient(int c) {
  NSString* dir = SslDirPath();
  SSL_CTX* ctx = SSL_CTX_new(TLS_server_method());
  if (!ctx) { close(c); return; }
  SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 |
                               SSL_OP_NO_TLSv1_1);
  if (SSL_CTX_use_certificate_chain_file(
          ctx, [[dir stringByAppendingPathComponent:@"cert.pem"] UTF8String]) != 1 ||
      SSL_CTX_use_PrivateKey_file(
          ctx, [[dir stringByAppendingPathComponent:@"key.pem"] UTF8String],
          SSL_FILETYPE_PEM) != 1) {
    SSL_CTX_free(ctx);
    close(c);
    return;
  }
  SSL* ssl = SSL_new(ctx);
  if (!ssl) { SSL_CTX_free(ctx); close(c); return; }
  SSL_set_fd(ssl, c);
  if (SSL_accept(ssl) != 1) {
    SSL_free(ssl);
    SSL_CTX_free(ctx);
    close(c);
    return;
  }
  PanelReq req;
  if (!ReadHttpRequest(ssl, req)) {
    SSL_free(ssl);
    SSL_CTX_free(ctx);
    close(c);
    return;
  }

  if (req.target.find("/install.mobileconfig") == 0) {
    NSData* body = MobileConfigData();
    std::string resp = "HTTP/1.1 200 OK\r\n"
                       "Content-Type: application/x-apple-aspen-config\r\n"
                       "Content-Length: " + std::to_string(body.length) + "\r\n"
                       "Connection: close\r\n"
                       "\r\n";
    SSL_write(ssl, resp.data(), resp.size());
    SSL_write(ssl, body.bytes, body.length);
  } else if (req.target.find("/home") == 0) {
    NSData* body = HomeHtmlData();
    std::string resp = "HTTP/1.1 200 OK\r\n"
                       "Content-Type: text/html; charset=utf-8\r\n"
                       "Content-Length: " + std::to_string(body.length) + "\r\n"
                       "Connection: close\r\n"
                       "\r\n";
    SSL_write(ssl, resp.data(), resp.size());
    SSL_write(ssl, body.bytes, body.length);
  } else {
    std::string up;
    if (ForwardToPanel(SettingInt(kConsolePort, 7070), req, up)) {
      SendPanelResponse(ssl, up);
    } else {
      std::string err = PanelErrorResponse();
      SSL_write(ssl, err.data(), err.size());
    }
  }
  SSL_free(ssl);
  SSL_CTX_free(ctx);
  close(c);
}

static void SslServerLoop(int port) {
  if (!SslHasCert()) return;
  int sock = socket(AF_INET, SOCK_STREAM, 0);
  if (sock < 0) return;
  int one = 1;
  setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons((uint16_t)port);
  addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  if (bind(sock, (struct sockaddr*)&addr, sizeof(addr)) != 0 ||
      listen(sock, 4) != 0) {
    close(sock);
    return;
  }
  while (!gSslStop.load()) {
    struct pollfd pfd;
    pfd.fd = sock;
    pfd.events = POLLIN;
    pfd.revents = 0;
    int pr = poll(&pfd, 1, 250);
    if (pr <= 0) continue;
    int c = accept(sock, nullptr, nullptr);
    if (c >= 0) std::thread([c]() { HandleClient(c); }).detach();
  }
  close(sock);
}

static void SslServerStart(int port) {
  if (gSslThread.joinable()) {
    gSslStop.store(true);
    gSslThread.join();
  }
  gSslStop.store(false);
  gSslThread = std::thread([port]() { SslServerLoop(port); });
}

static void SslServerStop(void) {
  gSslStop.store(true);
  if (gSslThread.joinable()) gSslThread.join();
}

// ---------------------------------------------------------------------------
// I2pSchemeHandler — WKURLSchemeHandler that fetches i2p-http / i2p-https
// requests through the local i2pd HTTP proxy at 127.0.0.1:<httpproxy port>.
// Eepsite TLS server certs are trusted for self-signed certificates.
// ---------------------------------------------------------------------------
@implementation I2pdSchemeHandler {
  NSMutableDictionary<NSNumber*, NSURLSessionDataTask*>* _tasks;
  NSURLSession* _session;
}

- (instancetype)init {
  self = [super init];
  if (self) {
    _tasks = [NSMutableDictionary dictionary];
    NSURLSessionConfiguration* cfg =
        [NSURLSessionConfiguration defaultSessionConfiguration];
    cfg.connectionProxyDictionary = @{
      @"HTTPEnable" : @YES,
      @"HTTPProxy" : @"127.0.0.1",
      @"HTTPPort" : @(SettingInt(kHttpPort, 4444)),
      @"HTTPSEnable" : @YES,
      @"HTTPSProxy" : @"127.0.0.1",
      @"HTTPSPort" : @(SettingInt(kHttpPort, 4444)),
    };
    cfg.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData;
    cfg.timeoutIntervalForRequest = 60;
    _session = [NSURLSession sessionWithConfiguration:cfg
                                             delegate:self
                                        delegateQueue:nil];
  }
  return self;
}

- (NSURL*)targetURLForTask:(id<WKURLSchemeTask>)task {
  NSURL* u = task.request.URL;
  NSURLComponents* c =
      [NSURLComponents componentsWithURL:u resolvingAgainstBaseURL:NO];
  c.scheme = [u.scheme isEqualToString:@"i2p-https"] ? @"https" : @"http";
  return c.URL;
}

- (void)webView:(WKWebView*)webView startURLSchemeTask:(id<WKURLSchemeTask>)task {
  NSURL* target = [self targetURLForTask:task];
  NSMutableURLRequest* req = [NSMutableURLRequest requestWithURL:target];
  NSDictionary* headers = task.request.allHTTPHeaderFields;
  for (NSString* key in headers) {
    if ([key caseInsensitiveCompare:@"Host"] == NSOrderedSame) continue;
    if ([key caseInsensitiveCompare:@"Accept-Encoding"] == NSOrderedSame) continue;
    if ([key caseInsensitiveCompare:@"Cookie"] == NSOrderedSame) continue;
    [req setValue:headers[key] forHTTPHeaderField:key];
  }
  [req setValue:nil forHTTPHeaderField:@"Accept-Encoding"];

  NSURLSessionDataTask* dt =
      [_session dataTaskWithRequest:req
                  completionHandler:^(NSData* data, NSURLResponse* resp,
                                      NSError* err) {
                    [_tasks removeObjectForKey:@(task.hash)];
                    if (err) {
                      [task didFailWithError:err];
                      return;
                    }
                    NSHTTPURLResponse* http = (NSHTTPURLResponse*)resp;
                    if (http.statusCode >= 400) {
                      [task didFailWithError:[NSError
                          errorWithDomain:NSURLErrorDomain
                                     code:http.statusCode
                                 userInfo:@{
                                   NSLocalizedDescriptionKey :
                                       [NSHTTPURLResponse
                                           localizedStringForStatusCode:
                                               http.statusCode]
                                 }]];
                      return;
                    }
                    NSURLResponse* out =
                        [[NSURLResponse alloc] initWithURL:task.request.URL
                                                  MIMEType:resp.MIMEType
                                     expectedContentLength:data.length
                                          textEncodingName:resp.textEncodingName];
                    [task didReceiveResponse:out];
                    if (data.length) [task didReceiveData:data];
                    [task didFinish];
                  }];
  if (dt) {
    _tasks[@(task.hash)] = dt;
    [dt resume];
  } else {
    [task didFailWithError:[NSError errorWithDomain:NSURLErrorDomain
                                               code:NSURLErrorCannotLoadFromNetwork
                                           userInfo:nil]];
  }
}

- (void)webView:(WKWebView*)webView stopURLSchemeTask:(id<WKURLSchemeTask>)task {
  NSURLSessionDataTask* dt = _tasks[@(task.hash)];
  if (dt) {
    [dt cancel];
    [_tasks removeObjectForKey:@(task.hash)];
  }
}

// Eepsites often use self-signed or unknown-CA certificates.
- (void)URLSession:(NSURLSession*)session
    didReceiveChallenge:(NSURLAuthenticationChallenge*)challenge
      completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition,
                                  NSURLCredential*))completionHandler {
  if ([challenge.protectionSpace.authenticationMethod
          isEqualToString:NSURLAuthenticationMethodServerTrust]) {
    SecTrustRef trust = challenge.protectionSpace.serverTrust;
    if (trust) {
      completionHandler(NSURLSessionAuthChallengeUseCredential,
                        [NSURLCredential credentialForTrust:trust]);
      return;
    }
  }
  completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
}

@end

// ---------------------------------------------------------------------------
// I2pdCore
// ---------------------------------------------------------------------------
@implementation I2pdCore

+ (void)prepare {
  OPENSSL_init_ssl(0, NULL);
}

// ---- settings ----
+ (BOOL)httpEnabled { return SettingBool(kHttpOn, YES); }
+ (void)setHttpEnabled:(BOOL)on { [UD() setBool:on forKey:kHttpOn]; }
+ (NSInteger)httpPort { return SettingInt(kHttpPort, 4444); }
+ (void)setHttpPort:(NSInteger)port { [UD() setInteger:port forKey:kHttpPort]; }
+ (BOOL)socksEnabled { return SettingBool(kSocksOn, YES); }
+ (void)setSocksEnabled:(BOOL)on { [UD() setBool:on forKey:kSocksOn]; }
+ (NSInteger)socksPort { return SettingInt(kSocksPort, 4447); }
+ (void)setSocksPort:(NSInteger)port { [UD() setInteger:port forKey:kSocksPort]; }
+ (BOOL)samEnabled { return SettingBool(kSamOn, YES); }
+ (void)setSamEnabled:(BOOL)on { [UD() setBool:on forKey:kSamOn]; }
+ (NSInteger)samPort { return SettingInt(kSamPort, 7656); }
+ (void)setSamPort:(NSInteger)port { [UD() setInteger:port forKey:kSamPort]; }
+ (NSString*)logLevel { return SettingString(kLogLevel, @"info"); }
+ (void)setLogLevel:(NSString*)level { [UD() setObject:level forKey:kLogLevel]; }
+ (NSString*)backloopHost {
  return SettingString(kBackloopHost, @"ios2pd.backloop.dev");
}
+ (void)setBackloopHost:(NSString*)host { [UD() setObject:host forKey:kBackloopHost]; }
+ (NSInteger)backloopPort { return SettingInt(kBackloopPort, 8443); }
+ (void)setBackloopPort:(NSInteger)port {
  [UD() setInteger:port forKey:kBackloopPort];
}
+ (BOOL)keepAliveEnabled { return SettingBool(kKeepAlive, NO); }
+ (void)setKeepAliveEnabled:(BOOL)on { [UD() setBool:on forKey:kKeepAlive]; }
+ (NSString*)ssid { return SettingString(kSsid, @""); }
+ (void)setSsid:(NSString*)ssid { [UD() setObject:ssid forKey:kSsid]; }
+ (NSInteger)consolePort { return SettingInt(kConsolePort, 7070); }
+ (void)setConsolePort:(NSInteger)port {
  [UD() setInteger:port forKey:kConsolePort];
}

// ---- config files ----
+ (NSString*)configDir { return ConfDir(); }
+ (NSString*)configPath { return ConfPath(); }
+ (NSString*)customConfigPath { return CustomConfPath(); }
+ (NSString*)customConfigText {
  NSString* s = [NSString stringWithContentsOfFile:CustomConfPath()
                                         encoding:NSUTF8StringEncoding
                                            error:nil];
  return s ?: @"";
}
+ (void)writeConfigFiles {
  WriteConfFile();
  WriteTunnelsFile();
}
+ (void)writeCustomConfig:(NSString*)text {
  EnsureConfDir();
  [text writeToFile:CustomConfPath() atomically:YES
           encoding:NSUTF8StringEncoding error:nil];
}

// ---- router ----
+ (BOOL)routerRunning { return gStarted.load(); }
+ (NSString*)routerLog {
  std::string text = TakeLog();
  if (text.empty()) return @"";
  return [NSString stringWithUTF8String:text.c_str()];
}
+ (NSString*)vpnStatus { return VpnStatusString(); }
+ (BOOL)startRouter {
  if (!StartDaemon()) return NO;
  InstallVpnProfile();
  return YES;
}
+ (void)stopRouter { StopDaemon(); }

// ---- tunnels ----
+ (NSArray<NSDictionary*>*)tunnels {
  return [TunnelsList() copy];
}
+ (void)saveTunnels:(NSArray<NSDictionary*>*)tunnels {
  SaveTunnels(tunnels ?: @[]);
}

// ---- keep alive ----
+ (void)applyKeepAlive { [[KeepAlive shared] apply]; }

// ---- backloop SSL + HTTPS server ----
+ (BOOL)hasSslCert { return SslHasCert(); }
+ (NSString*)sslExpiryString { return SslNotAfterString(); }
+ (BOOL)refreshSsl:(NSError**)error { return SslRefresh(error); }
+ (void)startSslServer {
  SslServerStart((int)[self backloopPort]);
}
+ (void)stopSslServer { SslServerStop(); }
+ (NSString* _Nullable)detectedSSID { return CurrentSSID(); }

@end
