//
//  ios2pd — i2pd (I2P daemon) as an iOS app.
//
//  Links the i2pd C++ daemon core (DaemonUnix) into a small UIKit shell.
//  The router runs on a background thread; logs are captured through a
//  custom std::ostream and surfaced in the UI.
//
//  Tabs:
//   - Router   : start/stop the daemon, VPN status, live log.
//   - Tunnels  : client/server tunnels (e.g. mail.i2p / Postman, IRC, ...).
//   - i2pd     : daemon settings (HTTP/SOCKS/SAM proxies, log level,
//                advanced i2pd.conf editor).
//   - Proxy    : backloop.dev integration - install a Wi-Fi proxy profile
//                (.mobileconfig), refresh the loopback SSL certificate, and
//                keep i2pd alive in the background.
//
//  The daemon is configured from two INI files that this app writes into
//  <Documents>/i2pd:
//    i2pd.conf     - basic settings from the UI + the user's custom block
//                    (appended verbatim from custom.conf).
//    tunnels.conf  - client/server tunnels edited in the Tunnels tab.
//  Both are passed via --conf / --tunconf on start.
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <NetworkExtension/NetworkExtension.h>
#import <AVFoundation/AVFoundation.h>
#import <QuartzCore/QuartzCore.h>
#import <SystemConfiguration/CaptiveNetwork.h>

#include <atomic>
#include <mutex>
#include <ostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <poll.h>
#include <unistd.h>
#include <cstring>

#include <openssl/ssl.h>
#include <openssl/err.h>

#include "Daemon.h"
#include "Log.h"
#include "Config.h"
#include "FS.h"

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------
static NSUserDefaults* UD() { return [NSUserDefaults standardUserDefaults]; }
static BOOL SettingBool(NSString* key, BOOL def) {
  id v = [UD() objectForKey:key];
  return v ? [v boolValue] : def;
}
static int SettingInt(NSString* key, int def) {
  id v = [UD() objectForKey:key];
  return v ? [v intValue] : def;
}
static NSString* SettingString(NSString* key, NSString* def) {
  NSString* v = [UD() stringForKey:key];
  return (v && v.length) ? v : def;
}

static NSString* const kHttpOn = @"i2pd_http_enabled";
static NSString* const kHttpPort = @"i2pd_http_port";
static NSString* const kSocksOn = @"i2pd_socks_enabled";
static NSString* const kSocksPort = @"i2pd_socks_port";
static NSString* const kSamOn = @"i2pd_sam_enabled";
static NSString* const kSamPort = @"i2pd_sam_port";
static NSString* const kLogLevel = @"i2pd_loglevel";
static NSString* const kBackloopHost = @"backloop_host";
static NSString* const kBackloopPort = @"backloop_https_port";
static NSString* const kKeepAlive = @"keepalive_audio";
static NSString* const kSslNotAfter = @"backloop_notafter";
static NSString* const kSsid = @"backloop_ssid";
static NSString* const kTunnels = @"tunnels";

// ---------------------------------------------------------------------------
// Config files (i2pd.conf + tunnels.conf) in <Documents>/i2pd
// ---------------------------------------------------------------------------
static NSString* ConfDir(void) {
  NSString* docs = [NSSearchPathForDirectoriesInDomains(
      NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
  return [docs stringByAppendingPathComponent:@"i2pd"];
}
static NSString* ConfPath(void) {
  return [ConfDir() stringByAppendingPathComponent:@"i2pd.conf"];
}
static NSString* TunnelsPath(void) {
  return [ConfDir() stringByAppendingPathComponent:@"tunnels.conf"];
}
static NSString* CustomConfPath(void) {
  return [ConfDir() stringByAppendingPathComponent:@"custom.conf"];
}

static BOOL EnsureConfDir(void) {
  NSFileManager* fm = [NSFileManager defaultManager];
  return [fm fileExistsAtPath:ConfDir()] ||
         [fm createDirectoryAtPath:ConfDir() withIntermediateDirectories:YES
                         attributes:nil error:nil];
}

// Persists the tunnels list (array of dicts) to NSUserDefaults.
static NSMutableArray* TunnelsList(void) {
  NSArray* stored = [UD() arrayForKey:kTunnels];
  return stored ? [stored mutableCopy] : [NSMutableArray array];
}
static void SaveTunnels(NSArray* list) {
  [UD() setObject:list forKey:kTunnels];
}

// Writes i2pd.conf from the UI settings + the user's custom.conf block.
static void WriteConfFile(void) {
  EnsureConfDir();
  NSMutableString* s = [NSMutableString string];
  [s appendString:@"# generated by ios2pd - edit via the app\n"];
  [s appendString:@"log = stdout\n"];
  [s appendFormat:@"loglevel = %@\n", SettingString(kLogLevel, @"info")];
  [s appendString:@"\n[httpproxy]\n"];
  [s appendFormat:@"enabled = %@\n", SettingBool(kHttpOn, YES) ? @"true" : @"false"];
  [s appendFormat:@"port = %d\n", SettingInt(kHttpPort, 4444)];
  [s appendString:@"\n[socksproxy]\n"];
  [s appendFormat:@"enabled = %@\n", SettingBool(kSocksOn, YES) ? @"true" : @"false"];
  [s appendFormat:@"port = %d\n", SettingInt(kSocksPort, 4447)];
  [s appendString:@"\n[sam]\n"];
  [s appendFormat:@"enabled = %@\n", SettingBool(kSamOn, YES) ? @"true" : @"false"];
  [s appendFormat:@"port = %d\n", SettingInt(kSamPort, 7656)];
  NSString* custom =
      [NSString stringWithContentsOfFile:CustomConfPath()
                                encoding:NSUTF8StringEncoding error:nil];
  if (custom.length) {
    [s appendString:@"\n# ---- user custom config ----\n"];
    [s appendString:custom];
    if (![custom hasSuffix:@"\n"]) [s appendString:@"\n"];
  }
  [s writeToFile:ConfPath() atomically:YES encoding:NSUTF8StringEncoding
           error:nil];
}

static void WriteTunnelsFile(void) {
  NSArray* tunnels = TunnelsList();
  if (!tunnels.count) return;
  EnsureConfDir();
  NSMutableString* s = [NSMutableString string];
  [s appendString:@"# tunnels configured in the ios2pd app\n"];
  for (NSDictionary* t in tunnels) {
    NSString* name = t[@"name"];
    if (!name.length) continue;
    NSString* type = t[@"type"] ?: @"client";
    [s appendFormat:@"\n[%@]\n", name];
    [s appendFormat:@"type = %@\n", type];
    if ([type isEqualToString:@"client"] || [type isEqualToString:@"socks"]) {
      [s appendFormat:@"address = %@\n", t[@"address"] ?: @"127.0.0.1"];
    }
    [s appendFormat:@"port = %@\n", t[@"port"] ?: @"0"];
    if ([type isEqualToString:@"client"]) {
      [s appendFormat:@"destination = %@\n", t[@"destination"] ?: @""];
      if ([t[@"keys"] length]) [s appendFormat:@"keys = %@\n", t[@"keys"]];
      if ([t[@"destinationport"] length])
        [s appendFormat:@"destinationport = %@\n", t[@"destinationport"]];
    } else if ([type isEqualToString:@"server"] ||
               [type isEqualToString:@"http"]) {
      [s appendFormat:@"host = %@\n", t[@"host"] ?: @"127.0.0.1"];
      if ([t[@"keys"] length]) [s appendFormat:@"keys = %@\n", t[@"keys"]];
      if ([t[@"inport"] length]) [s appendFormat:@"inport = %@\n", t[@"inport"]];
    } else if ([type isEqualToString:@"socks"]) {
      if ([t[@"keys"] length]) [s appendFormat:@"keys = %@\n", t[@"keys"]];
    }
  }
  [s writeToFile:TunnelsPath() atomically:YES encoding:NSUTF8StringEncoding
           error:nil];
}

// Best-effort read of the current Wi-Fi SSID. Requires the
// com.apple.developer.networking.wifi-info entitlement + location
// authorization on iOS 14+; returns nil otherwise (the user types it).
static NSString* CurrentSSID(void) {
  NSArray* ifs = (__bridge_transfer NSArray*)CNCopySupportedInterfaces();
  for (NSString* ifname in ifs) {
    NSDictionary* info = (__bridge_transfer NSDictionary*)
        CNCopyCurrentNetworkInfo((__bridge CFStringRef)ifname);
    NSString* ssid = info[(__bridge NSString*)kCNNetworkInfoKeySSID];
    if (ssid.length) return ssid;
  }
  return nil;
}

// ---------------------------------------------------------------------------
// Daemon bridge
// ---------------------------------------------------------------------------
namespace {

std::mutex gLogMutex;
std::string gLog;
std::atomic<bool> gStarted{false};
std::thread gDaemonThread;

// A streambuf that appends every byte written by i2pd's logger into gLog.
struct IosLogBuf : std::streambuf {
  int overflow(int c) override {
    if (c != EOF) {
      std::lock_guard<std::mutex> lock(gLogMutex);
      gLog.push_back(static_cast<char>(c));
      if (gLog.size() > (256 * 1024)) {
        gLog.erase(0, gLog.size() - (256 * 1024));
      }
    }
    return c;
  }
};

bool StartDaemon() {
  if (gStarted.load()) return true;

  WriteConfFile();
  WriteTunnelsFile();
  if (!EnsureConfDir()) return false;

  std::string datadir = std::string(ConfDir().UTF8String);
  std::vector<std::string> args = {
      "ios2pd",
      "--datadir=" + datadir,
      "--conf=" + std::string(ConfPath().UTF8String),
      "--log=stdout",
  };
  if (TunnelsList().count) {
    args.push_back("--tunconf=" + std::string(TunnelsPath().UTF8String));
  }

  std::vector<char*> argv;
  argv.reserve(args.size());
  for (auto& a : args) argv.push_back(&a[0]);

  static IosLogBuf logBuf;
  static std::ostream logStream(&logBuf);
  std::shared_ptr<std::ostream> sink(&logStream, [](std::ostream*) {});

  if (!Daemon.init(static_cast<int>(argv.size()), argv.data(), sink)) {
    return false;
  }
  if (!Daemon.start()) {
    return false;
  }
  gStarted.store(true);
  gDaemonThread = std::thread([]() { Daemon.run(); });
  return true;
}

void StopDaemon() {
  if (!gStarted.load()) return;
  Daemon.running = false;
  if (gDaemonThread.joinable()) gDaemonThread.join();
  Daemon.stop();
  gStarted.store(false);
}

std::string TakeLog() {
  std::lock_guard<std::mutex> lock(gLogMutex);
  return gLog;
}

// Installs (or updates) the NEAppProxyProvider VPN profile that routes *.i2p
// traffic through the local i2pd SOCKS proxy. Requires the
// com.apple.developer.networking.networkextension entitlement at signing time.
void InstallVpnProfile() {
  NEAppProxyProviderManager* mgr =
      (NEAppProxyProviderManager*)[NEAppProxyProviderManager sharedManager];
  [mgr loadFromPreferencesWithCompletionHandler:^(NSError* _Nullable err) {
    NETunnelProviderProtocol* proto = [[NETunnelProviderProtocol alloc] init];
    proto.providerBundleIdentifier = @"org.nouvborne.ios2pd.appproxy";
    proto.serverAddress = @"i2pd";
    proto.providerConfiguration = @{
      @"proxyHost" : @"127.0.0.1",
      @"proxyPort" : @(SettingInt(kSocksPort, 4447)),
    };
    mgr.protocolConfiguration = proto;
    mgr.localizedDescription = @"ios2pd I2P VPN";
    mgr.enabled = YES;
    [mgr saveToPreferencesWithCompletionHandler:^(NSError* _Nullable saveErr) {
      if (saveErr) {
        NSLog(@"[ios2pd] VPN profile save failed: %@", saveErr);
      }
    }];
  }];
}

NSString* VpnStatusString() {
  NEVPNConnection* conn = [NEAppProxyProviderManager sharedManager].connection;
  switch (conn.status) {
    case NEVPNStatusInvalid:
      return @"not configured";
    case NEVPNStatusDisconnected:
      return @"Disconnected";
    case NEVPNStatusConnecting:
      return @"Connecting";
    case NEVPNStatusConnected:
      return @"Connected";
    case NEVPNStatusReasserting:
      return @"Reconnecting";
    case NEVPNStatusDisconnecting:
      return @"Disconnecting";
  }
  return @"?";
}

}  // namespace

// ---------------------------------------------------------------------------
// Background keep-alive (silent audio so the proxy stays up in Safari)
// ---------------------------------------------------------------------------
@interface KeepAlive : NSObject
+ (instancetype)shared;
- (void)apply;
@end

@implementation KeepAlive {
  AVAudioPlayer* _player;
}

+ (instancetype)shared {
  static KeepAlive* instance;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    instance = [[KeepAlive alloc] init];
  });
  return instance;
}

// 1 second of 8 kHz mono 16-bit PCM silence as a WAV.
+ (NSData*)silentWavData {
  const int sr = 8000, ch = 1, bits = 16;
  const int samples = sr * 1;
  const int dataSize = samples * (bits / 8);
  NSMutableData* d = [NSMutableData dataWithCapacity:44 + dataSize];
  uint8_t hdr[44] = {0};
  hdr[0] = 'R'; hdr[1] = 'I'; hdr[2] = 'F'; hdr[3] = 'F';
  uint32_t u = 36 + dataSize; memcpy(hdr + 4, &u, 4);
  hdr[8] = 'W'; hdr[9] = 'A'; hdr[10] = 'V'; hdr[11] = 'E';
  hdr[12] = 'f'; hdr[13] = 'm'; hdr[14] = 't'; hdr[15] = ' ';
  u = 16; memcpy(hdr + 16, &u, 4);
  uint16_t s = 1; memcpy(hdr + 20, &s, 2);
  s = ch; memcpy(hdr + 22, &s, 2);
  u = sr; memcpy(hdr + 24, &u, 4);
  u = sr * ch * (bits / 8); memcpy(hdr + 28, &u, 4);
  s = ch * (bits / 8); memcpy(hdr + 32, &s, 2);
  s = bits; memcpy(hdr + 34, &s, 2);
  hdr[36] = 'd'; hdr[37] = 'a'; hdr[38] = 't'; hdr[39] = 'a';
  u = dataSize; memcpy(hdr + 40, &u, 4);
  [d appendBytes:hdr length:44];
  [d increaseLengthBy:dataSize];
  return d;
}

- (void)apply {
  BOOL on = SettingBool(kKeepAlive, NO);
  AVAudioSession* session = [AVAudioSession sharedInstance];
  if (on) {
    [session setCategory:AVAudioSessionCategoryPlayback error:nil];
    [session setActive:YES error:nil];
    if (!_player) {
      NSData* wav = [[self class] silentWavData];
      NSString* path = [NSTemporaryDirectory() stringByAppendingPathComponent:@"ios2pd-silence.wav"];
      [wav writeToFile:path atomically:YES];
      _player = [[AVAudioPlayer alloc] initWithContentsOfURL:[NSURL fileURLWithPath:path] error:nil];
      _player.numberOfLoops = -1;
      _player.volume = 0.0f;
      [_player prepareToPlay];
    }
    [_player play];
  } else {
    [_player stop];
    _player = nil;
    [session setActive:NO
           withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation
                 error:nil];
  }
}

@end

// ---------------------------------------------------------------------------
// backloop.dev SSL certificate + local HTTPS server
// ---------------------------------------------------------------------------
static NSString* SslDirPath(void) {
  NSString* docs = [NSSearchPathForDirectoriesInDomains(
      NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
  return [docs stringByAppendingPathComponent:@"backloop"];
}

static BOOL SslHasCert(void) {
  NSFileManager* fm = [NSFileManager defaultManager];
  NSString* dir = SslDirPath();
  return [fm fileExistsAtPath:[dir stringByAppendingPathComponent:@"cert.pem"]] &&
         [fm fileExistsAtPath:[dir stringByAppendingPathComponent:@"key.pem"]];
}

// Downloads the current *.backloop.dev wildcard cert/key from backloop.dev and
// stores them (cert+CA chain and key1+key2 concatenated) for the local HTTPS
// server. The cert is intentionally public - it only secures loopback.
static BOOL SslRefresh(NSError** errorOut) {
  NSURL* url = [NSURL URLWithString:@"https://backloop.dev/pack.json"];
  NSData* data = [NSData dataWithContentsOfURL:url
                                       options:NSDataReadingUncached
                                         error:errorOut];
  if (!data) return NO;
  NSError* jsonErr = nil;
  id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:&jsonErr];
  if (!parsed || ![parsed isKindOfClass:[NSDictionary class]]) {
    if (errorOut) *errorOut = jsonErr ?: [NSError errorWithDomain:@"ios2pd" code:1
        userInfo:@{NSLocalizedDescriptionKey : @"pack.json was not an object"}];
    return NO;
  }
  NSDictionary* pack = (NSDictionary*)parsed;
  NSString* cert = pack[@"cert"];
  NSString* ca = pack[@"ca"];
  NSString* k1 = pack[@"key1"];
  NSString* k2 = pack[@"key2"];
  if (!cert.length || !k1.length || !k2.length) {
    if (errorOut) *errorOut = [NSError errorWithDomain:@"ios2pd" code:2
        userInfo:@{NSLocalizedDescriptionKey : @"pack.json is missing cert/key fields"}];
    return NO;
  }
  NSString* bundle = ca.length ? [NSString stringWithFormat:@"%@\n%@", cert, ca]
                               : cert;
  NSString* key = [k1 stringByAppendingString:k2];
  NSFileManager* fm = [NSFileManager defaultManager];
  NSString* dir = SslDirPath();
  [fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];
  NSError* writeErr = nil;
  BOOL ok = [bundle writeToFile:[dir stringByAppendingPathComponent:@"cert.pem"]
                     atomically:YES encoding:NSUTF8StringEncoding error:&writeErr];
  ok = ok && [key writeToFile:[dir stringByAppendingPathComponent:@"key.pem"]
                   atomically:YES encoding:NSUTF8StringEncoding error:&writeErr];
  NSDictionary* info = pack[@"info"];
  if ([info isKindOfClass:[NSDictionary class]] && info[@"notAfter"]) {
    [UD() setObject:info[@"notAfter"] forKey:kSslNotAfter];
  }
  if (!ok && errorOut) *errorOut = writeErr;
  return ok;
}

static NSString* SslNotAfterString(void) {
  NSString* v = [UD() stringForKey:kSslNotAfter];
  if (!v.length) return @"not installed";
  NSDateFormatter* f = [[NSDateFormatter alloc] init];
  f.locale = [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"];
  f.dateFormat = @"yyyy-MM-dd'T'HH:mm:ss'Z'";
  f.timeZone = [NSTimeZone timeZoneForSecondsFromGMT:0];
  NSDate* d = [f dateFromString:v];
  if (!d) return v;
  NSDateFormatter* out = [[NSDateFormatter alloc] init];
  out.dateStyle = NSDateFormatterMediumStyle;
  out.timeStyle = NSDateFormatterShortStyle;
  return [out stringFromDate:d];
}

// Builds the Wi-Fi managed payload profile that points the HTTP proxy at the
// device's own loopback via a *.backloop.dev hostname. iOS requires SSID_STR
// for com.apple.wifi.managed, so the profile is keyed to the Wi-Fi network
// the user entered.
static NSData* MobileConfigData(NSError** errorOut) {
  NSString* host = SettingString(kBackloopHost, @"ios2pd.backloop.dev");
  int port = SettingInt(kHttpPort, 4444);
  NSString* ssid = SettingString(kSsid, @"");
  NSMutableDictionary* wifi = [NSMutableDictionary dictionary];
  wifi[@"PayloadType"] = @"com.apple.wifi.managed";
  wifi[@"PayloadVersion"] = @1;
  wifi[@"PayloadIdentifier"] = @"org.nouvborne.ios2pd.proxy.wifi";
  wifi[@"PayloadUUID"] = [NSUUID UUID].UUIDString;
  wifi[@"PayloadDisplayName"] = @"ios2pd I2P HTTP proxy";
  if (ssid.length) wifi[@"SSID_STR"] = ssid;
  wifi[@"ProxyType"] = @"Manual";
  wifi[@"ProxyServer"] = host;
  wifi[@"ProxyServerPort"] = @(port);

  NSMutableDictionary* profile = [NSMutableDictionary dictionary];
  profile[@"PayloadType"] = @"Configuration";
  profile[@"PayloadVersion"] = @1;
  profile[@"PayloadIdentifier"] = @"org.nouvborne.ios2pd.proxy";
  profile[@"PayloadUUID"] = [NSUUID UUID].UUIDString;
  profile[@"PayloadDisplayName"] = @"ios2pd I2P Proxy (backloop.dev)";
  profile[@"PayloadDescription"] =
      [NSString stringWithFormat:
          @"Sets the Wi-Fi HTTP proxy to %@:%d (resolves to this device's "
          @"loopback) so HTTP/HTTPS traffic is routed through the local i2pd "
          @"daemon running in the ios2pd app. Applies while connected to "
          @"\"%@\".",
          host, port, ssid.length ? ssid : @"your Wi-Fi"];
  profile[@"PayloadContent"] = @[ wifi ];
  return [NSPropertyListSerialization dataWithPropertyList:profile
                                                    format:NSPropertyListXMLFormat_v1_0
                                                   options:0
                                                     error:errorOut];
}

static NSData* HomeHtmlData(void) {
  NSString* host = SettingString(kBackloopHost, @"ios2pd.backloop.dev");
  int port = SettingInt(kHttpPort, 4444);
  NSString* html = [NSString stringWithFormat:
      @"<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" "
      @"content=\"width=device-width\"><title>ios2pd</title></head><body>"
      @"<h2>ios2pd local server</h2>"
      @"<p>This HTTPS server runs on this device (loopback via backloop.dev).</p>"
      @"<p><a href=\"/install.mobileconfig\">Install the I2P proxy profile</a></p>"
      @"<p>Proxy: <code>%@</code>:<code>%d</code></p>"
      @"<p>Start i2pd in the app, then browse <code>*.i2p</code> sites in Safari.</p>"
      @"</body></html>", host, port];
  return [html dataUsingEncoding:NSUTF8StringEncoding];
}

static std::atomic<bool> gSslStop{false};
static std::thread gSslThread;

// Handles one accepted connection: TLS handshake, then serves /install.mobileconfig.
static void HandleClient(int c) {
  NSString* dir = SslDirPath();
  SSL_CTX* ctx = SSL_CTX_new(TLS_server_method());
  if (!ctx) { close(c); return; }
  SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 |
                               SSL_OP_NO_TLSv1_1);
  if (SSL_CTX_use_certificate_chain_file(
          ctx, [[dir stringByAppendingPathComponent:@"cert.pem"] UTF8String]) != 1 ||
      SSL_CTX_use_PrivateKey_file(
          ctx, [[dir stringByAppendingPathComponent:@"key.pem"] UTF8String],
          SSL_FILETYPE_PEM) != 1) {
    SSL_CTX_free(ctx);
    close(c);
    return;
  }
  SSL* ssl = SSL_new(ctx);
  if (!ssl) { SSL_CTX_free(ctx); close(c); return; }
  SSL_set_fd(ssl, c);
  if (SSL_accept(ssl) != 1) {
    SSL_free(ssl);
    SSL_CTX_free(ctx);
    close(c);
    return;
  }
  char buf[16384];
  int n = SSL_read(ssl, buf, sizeof(buf) - 1);
  if (n > 0) {
    buf[n] = 0;
    std::string req(buf, n);
    std::string path = "/";
    size_t sp = req.find(' ');
    if (sp != std::string::npos) {
      size_t sp2 = req.find(' ', sp + 1);
      if (sp2 != std::string::npos) path = req.substr(sp + 1, sp2 - sp - 1);
    }
    NSData* body = nil;
    NSString* ctype = @"text/html; charset=utf-8";
    if (path == "/install.mobileconfig") {
      NSError* e = nil;
      body = MobileConfigData(&e);
      if (!body) body = [@"" dataUsingEncoding:NSUTF8StringEncoding];
      ctype = @"application/x-apple-aspen-config";
    } else {
      body = HomeHtmlData();
    }
    std::string resp = "HTTP/1.1 200 OK\r\n"
                       "Content-Type: " + std::string(ctype.UTF8String) + "\r\n"
                       "Content-Length: " + std::to_string(body.length) + "\r\n"
                       "Connection: close\r\n"
                       "\r\n";
    SSL_write(ssl, resp.data(), resp.size());
    SSL_write(ssl, body.bytes, body.length);
  }
  SSL_free(ssl);
  SSL_CTX_free(ctx);
  close(c);
}

static void SslServerLoop(int port) {
  if (!SslHasCert()) return;
  int sock = socket(AF_INET, SOCK_STREAM, 0);
  if (sock < 0) return;
  int one = 1;
  setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons((uint16_t)port);
  addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  if (bind(sock, (struct sockaddr*)&addr, sizeof(addr)) != 0 ||
      listen(sock, 4) != 0) {
    close(sock);
    return;
  }
  while (!gSslStop.load()) {
    struct pollfd pfd;
    pfd.fd = sock;
    pfd.events = POLLIN;
    pfd.revents = 0;
    int pr = poll(&pfd, 1, 250);
    if (pr <= 0) continue;
    int c = accept(sock, nullptr, nullptr);
    if (c >= 0) HandleClient(c);
  }
  close(sock);
}

static void SslServerStart(int port) {
  if (gSslThread.joinable()) {
    gSslStop.store(true);
    gSslThread.join();
  }
  gSslStop.store(false);
  gSslThread = std::thread([port]() { SslServerLoop(port); });
}

// ---------------------------------------------------------------------------
// Liquid-glass UI helpers
// ---------------------------------------------------------------------------
@interface GlassCard : UIVisualEffectView
@end
@implementation GlassCard
- (instancetype)initWithFrame:(CGRect)frame {
  self = [super initWithEffect:[UIBlurEffect effectWithStyle:UIBlurEffectStyleSystemMaterial]];
  if (self) {
    self.layer.cornerRadius = 22;
    self.layer.cornerCurve = kCACornerCurveContinuous;
    self.clipsToBounds = YES;
    self.layer.borderColor = [UIColor colorWithWhite:1.0 alpha:0.18].CGColor;
    self.layer.borderWidth = 1.0 / [UIScreen mainScreen].scale;
  }
  return self;
}
@end

@interface GradientButton : UIButton
@end
@implementation GradientButton {
  CAGradientLayer* _gradient;
}
- (void)layoutSubviews {
  [super layoutSubviews];
  if (!_gradient) {
    _gradient = [CAGradientLayer layer];
    _gradient.colors = @[
      (id)[UIColor systemBlueColor].CGColor,
      (id)[UIColor systemIndigoColor].CGColor,
    ];
    _gradient.startPoint = CGPointMake(0, 0);
    _gradient.endPoint = CGPointMake(1, 1);
    [self.layer insertSublayer:_gradient atIndex:0];
  }
  _gradient.frame = self.bounds;
  _gradient.cornerRadius = self.layer.cornerRadius;
}
@end

static void PinEdges(UIView* sub, UIView* sup, CGFloat top, CGFloat left,
                     CGFloat bottom, CGFloat right) {
  sub.translatesAutoresizingMaskIntoConstraints = NO;
  [NSLayoutConstraint activateConstraints:@[
    [sub.topAnchor constraintEqualToAnchor:sup.topAnchor constant:top],
    [sub.leadingAnchor constraintEqualToAnchor:sup.leadingAnchor constant:left],
    [sub.bottomAnchor constraintEqualToAnchor:sup.bottomAnchor constant:bottom],
    [sub.trailingAnchor constraintEqualToAnchor:sup.trailingAnchor constant:right],
  ]];
}

// ---------------------------------------------------------------------------
// Router tab
// ---------------------------------------------------------------------------
@interface RouterViewController : UIViewController
@end

@implementation RouterViewController {
  UILabel* _status;
  UILabel* _detail;
  UIButton* _toggle;
  UILabel* _vpn;
  UITextView* _log;
  NSTimer* _timer;
}

- (void)viewDidLoad {
  [super viewDidLoad];

  self.view.backgroundColor = [UIColor systemBackgroundColor];
  self.navigationItem.title = @"Router";

  UIView* root = self.view;
  UILayoutGuide* safe = root.safeAreaLayoutGuide;

  GlassCard* card = [[GlassCard alloc] initWithFrame:CGRectZero];
  [root addSubview:card];
  [NSLayoutConstraint activateConstraints:@[
    [card.topAnchor constraintEqualToAnchor:safe.topAnchor constant:16],
    [card.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:16],
    [card.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-16],
  ]];

  _status = [[UILabel alloc] initWithFrame:CGRectZero];
  _status.text = @"Stopped";
  _status.font = [UIFont systemFontOfSize:22 weight:UIFontWeightBold];
  _status.textColor = [UIColor labelColor];
  [card.contentView addSubview:_status];

  _detail = [[UILabel alloc] initWithFrame:CGRectZero];
  _detail.text = @"i2pd is not running";
  _detail.font = [UIFont systemFontOfSize:14];
  _detail.textColor = [UIColor secondaryLabelColor];
  [card.contentView addSubview:_detail];

  _toggle = [GradientButton buttonWithType:UIButtonTypeSystem];
  [_toggle setTitle:@"Start Router" forState:UIControlStateNormal];
  [_toggle setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
  _toggle.titleLabel.font = [UIFont systemFontOfSize:17 weight:UIFontWeightSemibold];
  _toggle.layer.cornerRadius = 16;
  [_toggle addTarget:self action:@selector(onToggle:) forControlEvents:UIControlEventTouchUpInside];
  [card.contentView addSubview:_toggle];

  [NSLayoutConstraint activateConstraints:@[
    [_status.topAnchor constraintEqualToAnchor:card.contentView.topAnchor constant:20],
    [_status.leadingAnchor constraintEqualToAnchor:card.contentView.leadingAnchor constant:20],
    [_status.trailingAnchor constraintEqualToAnchor:card.contentView.trailingAnchor constant:-20],
    [_detail.topAnchor constraintEqualToAnchor:_status.bottomAnchor constant:4],
    [_detail.leadingAnchor constraintEqualToAnchor:_status.leadingAnchor],
    [_detail.trailingAnchor constraintEqualToAnchor:_status.trailingAnchor],
    [_toggle.topAnchor constraintEqualToAnchor:_detail.bottomAnchor constant:16],
    [_toggle.leadingAnchor constraintEqualToAnchor:card.contentView.leadingAnchor constant:20],
    [_toggle.trailingAnchor constraintEqualToAnchor:card.contentView.trailingAnchor constant:-20],
    [_toggle.bottomAnchor constraintEqualToAnchor:card.contentView.bottomAnchor constant:-20],
    [_toggle.heightAnchor constraintEqualToConstant:52],
  ]];

  _vpn = [[UILabel alloc] initWithFrame:CGRectZero];
  _vpn.text = @"VPN: not configured";
  _vpn.font = [UIFont systemFontOfSize:13];
  _vpn.textColor = [UIColor secondaryLabelColor];
  _vpn.backgroundColor = [UIColor secondarySystemBackgroundColor];
  _vpn.layer.cornerRadius = 10;
  _vpn.clipsToBounds = YES;
  _vpn.textAlignment = NSTextAlignmentCenter;
  [root addSubview:_vpn];

  UILabel* logHeader = [[UILabel alloc] initWithFrame:CGRectZero];
  logHeader.text = @"Log";
  logHeader.font = [UIFont systemFontOfSize:13 weight:UIFontWeightSemibold];
  logHeader.textColor = [UIColor secondaryLabelColor];
  [root addSubview:logHeader];

  GlassCard* logCard = [[GlassCard alloc] initWithFrame:CGRectZero];
  [root addSubview:logCard];

  _log = [[UITextView alloc] initWithFrame:CGRectZero];
  _log.editable = NO;
  _log.selectable = YES;
  _log.font = [UIFont monospacedSystemFontOfSize:11 weight:UIFontWeightRegular];
  _log.textColor = [UIColor labelColor];
  _log.backgroundColor = [UIColor clearColor];
  _log.scrollIndicatorInsets = UIEdgeInsetsZero;
  [logCard.contentView addSubview:_log];

  [NSLayoutConstraint activateConstraints:@[
    [_vpn.topAnchor constraintEqualToAnchor:card.bottomAnchor constant:12],
    [_vpn.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:16],
    [_vpn.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-16],
    [_vpn.heightAnchor constraintEqualToConstant:34],
    [logHeader.topAnchor constraintEqualToAnchor:_vpn.bottomAnchor constant:16],
    [logHeader.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:18],
    [logCard.topAnchor constraintEqualToAnchor:logHeader.bottomAnchor constant:6],
    [logCard.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:16],
    [logCard.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-16],
    [logCard.bottomAnchor constraintEqualToAnchor:safe.bottomAnchor constant:-16],
  ]];
  PinEdges(_log, logCard.contentView, 10, 10, -10, -10);

  _timer = [NSTimer scheduledTimerWithTimeInterval:0.5
                                            target:self
                                          selector:@selector(refresh)
                                          userInfo:nil
                                           repeats:YES];
  [self refresh];
}

- (void)viewWillDisappear:(BOOL)animated {
  [super viewWillDisappear:animated];
  if ([self isMovingFromParentViewController] || self.tabBarController == nil) {
    [_timer invalidate];
  }
}

- (void)onToggle:(id)sender {
  if (gStarted.load()) {
    StopDaemon();
    _status.text = @"Stopped";
    _detail.text = @"i2pd is not running";
    [_toggle setTitle:@"Start Router" forState:UIControlStateNormal];
  } else {
    if (StartDaemon()) {
      _status.text = @"Starting…";
      _detail.text = @"Building tunnels";
      [_toggle setTitle:@"Stop Router" forState:UIControlStateNormal];
      InstallVpnProfile();
    } else {
      _detail.text = @"Failed to start - see log";
    }
  }
}

- (void)refresh {
  std::string text = TakeLog();
  if (!text.empty()) {
    NSString* s = [NSString stringWithUTF8String:text.c_str()];
    if (![_log.text isEqualToString:s]) {
      _log.text = s;
      [_log scrollRangeToVisible:NSMakeRange(_log.text.length - 1, 1)];
    }
  }
  if (gStarted.load()) {
    _status.text = @"Running";
    _detail.text = [NSString stringWithFormat:@"%zu tunnels configured",
                                              (size_t)TunnelsList().count];
  }
  _vpn.text = [NSString stringWithFormat:@"VPN: %@", VpnStatusString()];
}

@end

// ---------------------------------------------------------------------------
// Tunnels tab
// ---------------------------------------------------------------------------
@interface TunnelEditorViewController : UITableViewController <UITextFieldDelegate>
@property (nonatomic, strong) NSMutableDictionary* tunnel;
@property (nonatomic, assign) NSInteger editIndex;  // -1 when adding
- (instancetype)initWithTunnel:(NSMutableDictionary*)tunnel;
@end

@interface TunnelsViewController : UITableViewController
@end

@implementation TunnelsViewController

- (instancetype)init {
  self = [super initWithStyle:UITableViewStyleInsetGrouped];
  return self;
}

- (void)viewDidLoad {
  [super viewDidLoad];
  self.navigationItem.title = @"Tunnels";
  self.navigationItem.rightBarButtonItem =
      [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAdd
                                                    target:self
                                                    action:@selector(addTunnel:)];
}

- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];
  [self.tableView reloadData];
}

- (NSArray*)clientTunnels {
  NSMutableArray* a = [NSMutableArray array];
  for (NSDictionary* t in TunnelsList()) {
    NSString* type = t[@"type"] ?: @"client";
    if ([type isEqualToString:@"client"] || [type isEqualToString:@"socks"])
      [a addObject:t];
  }
  return a;
}
- (NSArray*)serverTunnels {
  NSMutableArray* a = [NSMutableArray array];
  for (NSDictionary* t in TunnelsList()) {
    NSString* type = t[@"type"] ?: @"client";
    if ([type isEqualToString:@"server"] || [type isEqualToString:@"http"])
      [a addObject:t];
  }
  return a;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView*)tableView {
  return 2;
}

- (NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section {
  return (section == 0) ? self.clientTunnels.count : self.serverTunnels.count;
}

- (NSString*)tableView:(UITableView*)tableView titleForHeaderInSection:(NSInteger)section {
  return (section == 0) ? @"Client tunnels (outgoing)" : @"Server tunnels (incoming)";
}

- (NSString*)tableView:(UITableView*)tableView titleForFooterInSection:(NSInteger)section {
  if (section == 0) {
    return @"Client tunnels expose a local port that forwards to an I2P "
           @"service - e.g. mail.i2p (Postman), IRC, etc.";
  }
  return @"Server tunnels publish a service running on this device to I2P. "
         @"Changes apply the next time you start the router.";
}

- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)ip {
  UITableViewCell* cell =
      [tableView dequeueReusableCellWithIdentifier:@"tunnel"];
  if (!cell) {
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle
                                  reuseIdentifier:@"tunnel"];
  }
  NSArray* list = (ip.section == 0) ? self.clientTunnels : self.serverTunnels;
  NSDictionary* t = list[ip.row];
  cell.textLabel.text = t[@"name"];
  cell.textLabel.font = [UIFont systemFontOfSize:16 weight:UIFontWeightSemibold];
  NSString* type = t[@"type"] ?: @"client";
  if ([type isEqualToString:@"client"]) {
    cell.detailTextLabel.text = [NSString stringWithFormat:@"client  %@:%@ -> %@",
                                 t[@"address"] ?: @"127.0.0.1", t[@"port"],
                                 t[@"destination"] ?: @"?"];
  } else if ([type isEqualToString:@"socks"]) {
    cell.detailTextLabel.text = [NSString stringWithFormat:@"socks  %@:%@",
                                 t[@"address"] ?: @"127.0.0.1", t[@"port"]];
  } else if ([type isEqualToString:@"http"]) {
    cell.detailTextLabel.text = [NSString stringWithFormat:@"http  <- %@:%@",
                                 t[@"host"] ?: @"127.0.0.1", t[@"port"]];
  } else {
    cell.detailTextLabel.text = [NSString stringWithFormat:@"server  <- %@:%@",
                                 t[@"host"] ?: @"127.0.0.1", t[@"port"]];
  }
  cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
  return cell;
}

- (void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)ip {
  [tableView deselectRowAtIndexPath:ip animated:YES];
  NSArray* list = (ip.section == 0) ? self.clientTunnels : self.serverTunnels;
  NSDictionary* t = list[ip.row];
  NSArray* all = TunnelsList();
  NSInteger idx = [all indexOfObjectIdenticalTo:t];
  TunnelEditorViewController* ed =
      [[TunnelEditorViewController alloc] initWithTunnel:[t mutableCopy]];
  ed.editIndex = idx;
  [self.navigationController pushViewController:ed animated:YES];
}

- (BOOL)tableView:(UITableView*)tableView canEditRowAtIndexPath:(NSIndexPath*)ip {
  return YES;
}

- (void)tableView:(UITableView*)tableView commitEditingStyle:(UITableViewCellEditingStyle)style
    forRowAtIndexPath:(NSIndexPath*)ip {
  if (style == UITableViewCellEditingStyleDelete) {
    NSArray* list = (ip.section == 0) ? self.clientTunnels : self.serverTunnels;
    NSDictionary* t = list[ip.row];
    NSMutableArray* all = TunnelsList();
    [all removeObjectIdenticalTo:t];
    SaveTunnels(all);
    [tableView deleteRowsAtIndexPaths:@[ ip ]
                     withRowAnimation:UITableViewRowAnimationAutomatic];
  }
}

- (void)addTunnel:(id)sender {
  UIAlertController* sheet =
      [UIAlertController alertControllerWithTitle:@"Add tunnel"
                                          message:nil
                                   preferredStyle:UIAlertControllerStyleActionSheet];
  void (^pushNew)(NSString*, NSString*) = ^(NSString* type, NSString* name) {
    NSMutableDictionary* t = [NSMutableDictionary dictionary];
    t[@"type"] = type;
    t[@"name"] = name;
    t[@"port"] = @"0";
    t[@"address"] = @"127.0.0.1";
    TunnelEditorViewController* ed =
        [[TunnelEditorViewController alloc] initWithTunnel:t];
    ed.editIndex = -1;
    [self.navigationController pushViewController:ed animated:YES];
  };
  [sheet addAction:[UIAlertAction actionWithTitle:@"Client tunnel (to an I2P service)"
                                            style:UIAlertActionStyleDefault
                                          handler:^(UIAlertAction* a) {
                                            pushNew(@"client", @"new-client");
                                          }]];
  [sheet addAction:[UIAlertAction actionWithTitle:@"Server tunnel (host a service)"
                                            style:UIAlertActionStyleDefault
                                          handler:^(UIAlertAction* a) {
                                            pushNew(@"server", @"new-server");
                                          }]];
  [sheet addAction:[UIAlertAction actionWithTitle:@"HTTP tunnel"
                                            style:UIAlertActionStyleDefault
                                          handler:^(UIAlertAction* a) {
                                            pushNew(@"http", @"new-http");
                                          }]];
  [sheet addAction:[UIAlertAction actionWithTitle:@"Postman e-mail preset (mail.i2p)"
                                            style:UIAlertActionStyleDefault
                                          handler:^(UIAlertAction* a) {
                                            [self addPostmanPreset];
                                          }]];
  [sheet addAction:[UIAlertAction actionWithTitle:@"Cancel"
                                            style:UIAlertActionStyleCancel
                                          handler:nil]];
  if (sheet.popoverPresentationController) {
    sheet.popoverPresentationController.barButtonItem = sender;
  }
  [self presentViewController:sheet animated:YES completion:nil];
}

- (void)addPostmanPreset {
  NSMutableArray* all = TunnelsList();
  [all addObject:@{
    @"name" : @"mail-smtp",
    @"type" : @"client",
    @"address" : @"127.0.0.1",
    @"port" : @"515",
    @"destination" : @"smtp.postman.i2p",
    @"keys" : @"mail.dat",
  }];
  [all addObject:@{
    @"name" : @"mail-pop3",
    @"type" : @"client",
    @"address" : @"127.0.0.1",
    @"port" : @"616",
    @"destination" : @"pop.postman.i2p",
    @"keys" : @"mail.dat",
  }];
  SaveTunnels(all);
  [self.tableView reloadData];
}

@end

@implementation TunnelEditorViewController

- (instancetype)initWithTunnel:(NSMutableDictionary*)tunnel {
  self = [super initWithStyle:UITableViewStyleInsetGrouped];
  if (self) {
    _tunnel = tunnel;
    _editIndex = -1;
  }
  return self;
}

- (void)viewDidLoad {
  [super viewDidLoad];
  self.navigationItem.title = @"Edit tunnel";
  self.navigationItem.rightBarButtonItem =
      [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemSave
                                                    target:self
                                                    action:@selector(save:)];
  self.tableView.keyboardDismissMode = UIScrollViewKeyboardDismissModeOnDrag;
}

- (NSArray*)visibleRows {
  NSString* type = _tunnel[@"type"] ?: @"client";
  NSMutableArray* r = [NSMutableArray arrayWithArray:@[ @"name", @"type", @"port" ]];
  if ([type isEqualToString:@"client"] || [type isEqualToString:@"socks"]) {
    [r addObject:@"address"];
  }
  if ([type isEqualToString:@"client"]) {
    [r addObject:@"destination"];
    [r addObject:@"destinationport"];
  }
  if ([type isEqualToString:@"server"] || [type isEqualToString:@"http"]) {
    [r addObject:@"host"];
    [r addObject:@"inport"];
  }
  [r addObject:@"keys"];
  return r;
}

- (NSString*)labelForKey:(NSString*)key {
  static NSDictionary* labels;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    labels = @{
      @"name" : @"Name",
      @"type" : @"Type",
      @"port" : @"Local port",
      @"address" : @"Bind address",
      @"destination" : @"Destination (.i2p)",
      @"destinationport" : @"Destination port",
      @"host" : @"Host",
      @"inport" : @"I2P inport",
      @"keys" : @"Keys file",
    };
  });
  return labels[key] ?: key;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView*)tableView {
  return 1;
}

- (NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section {
  return self.visibleRows.count;
}

- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)ip {
  NSString* key = self.visibleRows[ip.row];
  if ([key isEqualToString:@"type"]) {
    UITableViewCell* cell =
        [tableView dequeueReusableCellWithIdentifier:@"type"];
    if (!cell) {
      cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1
                                    reuseIdentifier:@"type"];
    }
    cell.textLabel.text = @"Type";
    cell.detailTextLabel.text = _tunnel[@"type"] ?: @"client";
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    return cell;
  }
  NSString* cellId = @"field";
  UITableViewCell* cell = [tableView dequeueReusableCellWithIdentifier:cellId];
  if (!cell) {
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault
                                  reuseIdentifier:cellId];
  }
  cell.selectionStyle = UITableViewCellSelectionStyleNone;
  cell.accessoryView = nil;
  for (UIView* sub in cell.contentView.subviews) {
    if ([sub isKindOfClass:[UITextField class]]) [sub removeFromSuperview];
  }
  cell.textLabel.text = [self labelForKey:key];
  UITextField* f = [[UITextField alloc] initWithFrame:CGRectZero];
  f.delegate = self;
  f.returnKeyType = UIReturnKeyDone;
  f.autocorrectionType = UITextAutocorrectionTypeNo;
  f.autocapitalizationType = UITextAutocapitalizationTypeNone;
  NSString* val = _tunnel[key];
  if ([val isKindOfClass:[NSNumber class]]) val = [(NSNumber*)val stringValue];
  f.text = val;
  f.textAlignment = NSTextAlignmentRight;
  BOOL numeric = [key isEqualToString:@"port"] || [key isEqualToString:@"destinationport"] ||
                 [key isEqualToString:@"inport"];
  f.keyboardType = numeric ? UIKeyboardTypeNumberPad : UIKeyboardTypeDefault;
  f.clearButtonMode = UITextFieldViewModeWhileEditing;
  [cell.contentView addSubview:f];
  [f setContentHuggingPriority:UILayoutPriorityRequired
                        forAxis:UILayoutConstraintAxisHorizontal];
  [f setContentCompressionResistancePriority:UILayoutPriorityDefaultLow
                                      forAxis:UILayoutConstraintAxisHorizontal];
  [NSLayoutConstraint activateConstraints:@[
    [f.centerYAnchor constraintEqualToAnchor:cell.contentView.centerYAnchor],
    [f.leadingAnchor constraintEqualToAnchor:cell.textLabel.trailingAnchor constant:12],
    [f.trailingAnchor constraintEqualToAnchor:cell.contentView.trailingAnchor constant:-16],
  ]];
  return cell;
}

- (void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)ip {
  [tableView deselectRowAtIndexPath:ip animated:YES];
  NSString* key = self.visibleRows[ip.row];
  if (![key isEqualToString:@"type"]) return;
  UIAlertController* sheet =
      [UIAlertController alertControllerWithTitle:@"Tunnel type"
                                          message:nil
                                   preferredStyle:UIAlertControllerStyleActionSheet];
  for (NSString* type in @[ @"client", @"server", @"http", @"socks" ]) {
    [sheet addAction:[UIAlertAction actionWithTitle:type
                                              style:UIAlertActionStyleDefault
                                            handler:^(UIAlertAction* a) {
                                              _tunnel[@"type"] = type;
                                              [self.tableView reloadData];
                                            }]];
  }
  [sheet addAction:[UIAlertAction actionWithTitle:@"Cancel"
                                            style:UIAlertActionStyleCancel
                                          handler:nil]];
  [self presentViewController:sheet animated:YES completion:nil];
}

- (BOOL)textFieldShouldReturn:(UITextField*)field {
  [field resignFirstResponder];
  return YES;
}

- (void)textFieldDidEndEditing:(UITextField*)field {
  UIView* v = field;
  while (v && ![v isKindOfClass:[UITableViewCell class]]) v = v.superview;
  UITableViewCell* cell = (UITableViewCell*)v;
  NSIndexPath* ip = cell ? [self.tableView indexPathForCell:cell] : nil;
  if (!ip) return;
  NSString* key = self.visibleRows[ip.row];
  _tunnel[key] = field.text;
}

- (void)save:(id)sender {
  NSString* name = [_tunnel[@"name"] stringByTrimmingCharactersInSet:
      [NSCharacterSet whitespaceCharacterSet]];
  if (!name.length) {
    [self alert:@"Give the tunnel a name."];
    return;
  }
  int port = [_tunnel[@"port"] intValue];
  if (port < 1 || port > 65535) {
    [self alert:@"Enter a valid local port (1-65535)."];
    return;
  }
  NSString* type = _tunnel[@"type"] ?: @"client";
  if ([type isEqualToString:@"client"] &&
      ![[_tunnel[@"destination"] stringByTrimmingCharactersInSet:
          [NSCharacterSet whitespaceCharacterSet]] length]) {
    [self alert:@"Client tunnels need a destination (e.g. smtp.postman.i2p)."];
    return;
  }
  _tunnel[@"name"] = name;
  NSMutableArray* all = TunnelsList();
  if (_editIndex >= 0 && _editIndex < (NSInteger)all.count) {
    all[_editIndex] = _tunnel;
  } else {
    [all addObject:_tunnel];
  }
  SaveTunnels(all);
  [self.navigationController popViewControllerAnimated:YES];
}

- (void)alert:(NSString*)message {
  UIAlertController* a = [UIAlertController alertControllerWithTitle:@"ios2pd"
                                                              message:message
                                                       preferredStyle:UIAlertControllerStyleAlert];
  [a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];
  [self presentViewController:a animated:YES completion:nil];
}

@end

// ---------------------------------------------------------------------------
// i2pd settings tab
// ---------------------------------------------------------------------------
@interface CustomConfViewController : UIViewController
@end

@implementation CustomConfViewController {
  UITextView* _tv;
}

- (void)viewDidLoad {
  [super viewDidLoad];
  self.view.backgroundColor = [UIColor systemBackgroundColor];
  self.navigationItem.title = @"Advanced config";
  self.navigationItem.rightBarButtonItem =
      [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemSave
                                                    target:self
                                                    action:@selector(save:)];

  UILabel* hint = [[UILabel alloc] initWithFrame:CGRectZero];
  hint.text = @"Appended to i2pd.conf. INI syntax: key = value, sections like "
              @"[httpproxy]. Command-line flags win over this file. "
              @"Restart the router to apply.";
  hint.font = [UIFont systemFontOfSize:12];
  hint.textColor = [UIColor secondaryLabelColor];
  hint.numberOfLines = 0;
  [self.view addSubview:hint];

  _tv = [[UITextView alloc] initWithFrame:CGRectZero];
  _tv.font = [UIFont monospacedSystemFontOfSize:13 weight:UIFontWeightRegular];
  _tv.textColor = [UIColor labelColor];
  _tv.backgroundColor = [UIColor secondarySystemBackgroundColor];
  _tv.layer.cornerRadius = 12;
  _tv.keyboardDismissMode = UIScrollViewKeyboardDismissModeInteractive;
  _tv.text = [NSString stringWithContentsOfFile:CustomConfPath()
                                       encoding:NSUTF8StringEncoding error:nil] ?: @"";
  [self.view addSubview:_tv];

  UILayoutGuide* safe = self.view.safeAreaLayoutGuide;
  [NSLayoutConstraint activateConstraints:@[
    [hint.topAnchor constraintEqualToAnchor:safe.topAnchor constant:12],
    [hint.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:16],
    [hint.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-16],
    [_tv.topAnchor constraintEqualToAnchor:hint.bottomAnchor constant:8],
    [_tv.leadingAnchor constraintEqualToAnchor:safe.leadingAnchor constant:16],
    [_tv.trailingAnchor constraintEqualToAnchor:safe.trailingAnchor constant:-16],
    [_tv.bottomAnchor constraintEqualToAnchor:safe.bottomAnchor constant:-16],
  ]];
}

- (void)save:(id)sender {
  EnsureConfDir();
  [_tv.text writeToFile:CustomConfPath() atomically:YES
               encoding:NSUTF8StringEncoding error:nil];
  [self.navigationController popViewControllerAnimated:YES];
}

@end

@interface I2pdSettingsViewController : UITableViewController <UITextFieldDelegate>
@end

@implementation I2pdSettingsViewController

- (instancetype)init {
  self = [super initWithStyle:UITableViewStyleInsetGrouped];
  return self;
}

- (void)viewDidLoad {
  [super viewDidLoad];
  self.navigationItem.title = @"i2pd";
  self.tableView.keyboardDismissMode = UIScrollViewKeyboardDismissModeOnDrag;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView*)tableView {
  return 4;
}

- (NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section {
  switch (section) {
    case 0: return 2;  // HTTP proxy
    case 1: return 2;  // SOCKS proxy
    case 2: return 2;  // SAM
    case 3: return 2;  // log level + advanced config
    default: return 0;
  }
}

- (NSString*)tableView:(UITableView*)tableView titleForHeaderInSection:(NSInteger)section {
  switch (section) {
    case 0: return @"HTTP proxy (browsers)";
    case 1: return @"SOCKS5 proxy";
    case 2: return @"SAM";
    case 3: return @"Logging & advanced";
    default: return nil;
  }
}

- (NSString*)tableView:(UITableView*)tableView titleForFooterInSection:(NSInteger)section {
  switch (section) {
    case 0: return @"Used by the Wi-Fi proxy profile and by browsers on this device.";
    case 1: return @"Used by the optional VPN extension to tunnel *.i2p flows.";
    case 3: return @"Changes apply the next time you start the router.";
    default: return nil;
  }
}

- (UITextField*)portFieldWithTag:(NSInteger)tag value:(NSInteger)value {
  UITextField* f = [[UITextField alloc] initWithFrame:CGRectZero];
  f.tag = 1000 + ((tag - 100) / 10);
  f.text = [NSString stringWithFormat:@"%ld", (long)value];
  f.keyboardType = UIKeyboardTypeNumberPad;
  f.textAlignment = NSTextAlignmentRight;
  f.returnKeyType = UIReturnKeyDone;
  f.delegate = self;
  return f;
}

- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)ip {
  NSInteger section = ip.section;
  NSInteger row = ip.row;

  if (section == 3 && row == 1) {
    UITableViewCell* cell =
        [tableView dequeueReusableCellWithIdentifier:@"adv"];
    if (!cell) {
      cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1
                                    reuseIdentifier:@"adv"];
    }
    cell.textLabel.text = @"Advanced config";
    cell.detailTextLabel.text = @"i2pd.conf";
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    return cell;
  }

  BOOL isSwitch = (row == 0);
  NSString* title;
  if (isSwitch) {
    switch (section) {
      case 0: title = @"Enabled"; break;
      case 1: title = @"Enabled"; break;
      case 2: title = @"Enabled"; break;
      default: title = @""; break;
    }
  } else {
    switch (section) {
      case 0: title = @"Port"; break;
      case 1: title = @"Port"; break;
      case 2: title = @"Port"; break;
      default: title = @""; break;
    }
  }
  NSString* cellId = isSwitch ? @"sw" : @"txt";
  UITableViewCell* cell = [tableView dequeueReusableCellWithIdentifier:cellId];
  if (!cell) {
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellId];
  }
  cell.textLabel.text = title;
  cell.selectionStyle = UITableViewCellSelectionStyleNone;
  cell.accessoryView = nil;
  for (UIView* sub in cell.contentView.subviews) {
    if ([sub isKindOfClass:[UITextField class]]) [sub removeFromSuperview];
  }

  if (section == 3) {
    // Log level segmented control
    cell.textLabel.text = @"Level";
    UISegmentedControl* seg = [[UISegmentedControl alloc] initWithItems:@[ @"info", @"debug", @"warn", @"error" ]];
    seg.frame = CGRectMake(0, 0, 220, 30);
    NSString* lvl = SettingString(kLogLevel, @"info");
    seg.selectedSegmentIndex = [@[ @"info", @"debug", @"warn", @"error" ] indexOfObject:lvl];
    if (seg.selectedSegmentIndex == NSNotFound) seg.selectedSegmentIndex = 0;
    [seg addTarget:self action:@selector(logLevelChanged:) forControlEvents:UIControlEventValueChanged];
    cell.accessoryView = seg;
    return cell;
  }

  NSInteger tag = section * 10 + row + 100;
  if (isSwitch) {
    UISwitch* sw = [[UISwitch alloc] init];
    sw.tag = tag;
    BOOL on = NO;
    if (section == 0) on = SettingBool(kHttpOn, YES);
    else if (section == 1) on = SettingBool(kSocksOn, YES);
    else if (section == 2) on = SettingBool(kSamOn, YES);
    sw.on = on;
    [sw addTarget:self action:@selector(switchChanged:) forControlEvents:UIControlEventValueChanged];
    cell.accessoryView = sw;
  } else {
    int value = 0;
    if (section == 0) value = SettingInt(kHttpPort, 4444);
    else if (section == 1) value = SettingInt(kSocksPort, 4447);
    else if (section == 2) value = SettingInt(kSamPort, 7656);
    UITextField* f = [self portFieldWithTag:tag value:value];
    [cell.contentView addSubview:f];
    [f setContentHuggingPriority:UILayoutPriorityRequired
                          forAxis:UILayoutConstraintAxisHorizontal];
    [f setContentCompressionResistancePriority:UILayoutPriorityDefaultLow
                                        forAxis:UILayoutConstraintAxisHorizontal];
    [NSLayoutConstraint activateConstraints:@[
      [f.centerYAnchor constraintEqualToAnchor:cell.contentView.centerYAnchor],
      [f.leadingAnchor constraintEqualToAnchor:cell.textLabel.trailingAnchor constant:12],
      [f.trailingAnchor constraintEqualToAnchor:cell.contentView.trailingAnchor constant:-16],
    ]];
  }
  return cell;
}

- (void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)ip {
  [tableView deselectRowAtIndexPath:ip animated:YES];
  if (ip.section == 3 && ip.row == 1) {
    [self.navigationController pushViewController:[[CustomConfViewController alloc] init]
                                         animated:YES];
  }
}

- (void)switchChanged:(UISwitch*)sw {
  NSInteger section = (sw.tag - 100) / 10;
  switch (section) {
    case 0: [UD() setBool:sw.on forKey:kHttpOn]; break;
    case 1: [UD() setBool:sw.on forKey:kSocksOn]; break;
    case 2: [UD() setBool:sw.on forKey:kSamOn]; break;
  }
}

- (void)logLevelChanged:(UISegmentedControl*)seg {
  NSArray* levels = @[ @"info", @"debug", @"warn", @"error" ];
  NSInteger i = seg.selectedSegmentIndex;
  [UD() setObject:(i >= 0 && i < levels.count) ? levels[i] : @"info" forKey:kLogLevel];
}

- (void)textFieldDidEndEditing:(UITextField*)field {
  NSInteger section = field.tag - 1000;
  int port = [field.text intValue];
  if (port < 1 || port > 65535) {
    int def = (section == 0) ? 4444 : (section == 1) ? 4447 : 7656;
    port = def;
    field.text = [NSString stringWithFormat:@"%d", port];
  }
  NSString* key = (section == 0) ? kHttpPort : (section == 1) ? kSocksPort : kSamPort;
  [UD() setInteger:port forKey:key];
}

- (BOOL)textFieldShouldReturn:(UITextField*)field {
  [field resignFirstResponder];
  return YES;
}

@end

// ---------------------------------------------------------------------------
// Proxy / app settings tab
// ---------------------------------------------------------------------------
@interface AppSettingsViewController : UITableViewController <UITextFieldDelegate>
@property (nonatomic, assign) BOOL busy;
@end

@implementation AppSettingsViewController

- (instancetype)init {
  self = [super initWithStyle:UITableViewStyleInsetGrouped];
  return self;
}

- (void)viewDidLoad {
  [super viewDidLoad];
  self.navigationItem.title = @"Proxy";
  self.tableView.keyboardDismissMode = UIScrollViewKeyboardDismissModeOnDrag;
}

- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];
  if (!SettingString(kSsid, @"").length) {
    NSString* ssid = CurrentSSID();
    if (ssid.length) {
      [UD() setObject:ssid forKey:kSsid];
    }
  }
  [self.tableView reloadData];
}

- (NSInteger)numberOfSectionsInTableView:(UITableView*)tableView {
  return 5;
}

- (NSInteger)tableView:(UITableView*)tableView numberOfRowsInSection:(NSInteger)section {
  switch (section) {
    case 0: return 2;  // host, https port
    case 1: return 1;  // Wi-Fi SSID
    case 2: return 2;  // ssl expiry, update
    case 3: return 1;  // install profile
    case 4: return 1;  // keep alive
    default: return 0;
  }
}

- (NSString*)tableView:(UITableView*)tableView titleForHeaderInSection:(NSInteger)section {
  switch (section) {
    case 0: return @"backloop.dev proxy";
    case 1: return @"Wi-Fi network";
    case 2: return @"SSL certificate";
    case 3: return @"Proxy profile";
    case 4: return @"General";
    default: return nil;
  }
}

- (NSString*)tableView:(UITableView*)tableView titleForFooterInSection:(NSInteger)section {
  switch (section) {
    case 0:
      return @"backloop.dev is a wildcard domain pointing at 127.0.0.1 with a "
             @"publicly trusted certificate. The app serves HTTPS on this "
             @"device so Safari can install the profile over a trusted link.";
    case 1:
      return @"iOS requires the exact SSID of the Wi-Fi you are on for the "
             @"proxy profile. Enter it if it was not detected automatically. "
             @"The profile only applies while connected to this network.";
    case 2:
      return @"The loopback certificate is refreshed weekly by backloop.dev. "
             @"Update it if the certificate has expired.";
    case 3:
      return @"Installs a Wi-Fi profile that routes HTTP/HTTPS through the "
             @"local i2pd proxy (start the router first). Requires Wi-Fi; "
             @"i2pd must keep running while you browse.";
    case 4:
      return @"Without keep-alive, iOS suspends the app and the proxy stops. "
             @"Keep-alive plays silent audio so i2pd stays up in the "
             @"background (battery impact).";
    default: return nil;
  }
}

- (void)updateBusy:(BOOL)busy {
  self.busy = busy;
  [self.tableView reloadRowsAtIndexPaths:@[
    [NSIndexPath indexPathForRow:1 inSection:2],
    [NSIndexPath indexPathForRow:0 inSection:3],
  ]
                        withRowAnimation:UITableViewRowAnimationNone];
}

- (UITableViewCell*)cellForTextField:(UITableView*)tableView indexPath:(NSIndexPath*)ip {
  NSString* cellId = [NSString stringWithFormat:@"f%ld-%ld", (long)ip.section, (long)ip.row];
  UITableViewCell* cell = [tableView dequeueReusableCellWithIdentifier:cellId];
  if (!cell) {
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellId];
  }
  cell.selectionStyle = UITableViewCellSelectionStyleNone;
  cell.accessoryView = nil;
  for (UIView* sub in cell.contentView.subviews) {
    if ([sub isKindOfClass:[UITextField class]]) [sub removeFromSuperview];
  }
  return cell;
}

- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)ip {
  if (ip.section == 0) {
    UITableViewCell* cell = [self cellForTextField:tableView indexPath:ip];
    cell.textLabel.text = (ip.row == 0) ? @"Hostname" : @"HTTPS port";
    UITextField* f = [[UITextField alloc] initWithFrame:CGRectZero];
    f.tag = 2000 + ip.row;
    if (ip.row == 0) {
      f.text = SettingString(kBackloopHost, @"ios2pd.backloop.dev");
      f.autocorrectionType = UITextAutocorrectionTypeNo;
      f.autocapitalizationType = UITextAutocapitalizationTypeNone;
      f.keyboardType = UIKeyboardTypeURL;
    } else {
      f.text = [NSString stringWithFormat:@"%d", SettingInt(kBackloopPort, 8443)];
      f.keyboardType = UIKeyboardTypeNumberPad;
      f.textAlignment = NSTextAlignmentRight;
    }
    f.returnKeyType = UIReturnKeyDone;
    f.delegate = self;
    [cell.contentView addSubview:f];
    [f setContentHuggingPriority:UILayoutPriorityRequired
                          forAxis:UILayoutConstraintAxisHorizontal];
    [f setContentCompressionResistancePriority:UILayoutPriorityDefaultLow
                                        forAxis:UILayoutConstraintAxisHorizontal];
    [NSLayoutConstraint activateConstraints:@[
      [f.centerYAnchor constraintEqualToAnchor:cell.contentView.centerYAnchor],
      [f.leadingAnchor constraintEqualToAnchor:cell.textLabel.trailingAnchor constant:12],
      [f.trailingAnchor constraintEqualToAnchor:cell.contentView.trailingAnchor constant:-16],
    ]];
    return cell;
  }

  if (ip.section == 1) {
    UITableViewCell* cell = [self cellForTextField:tableView indexPath:ip];
    cell.textLabel.text = @"SSID";
    UITextField* f = [[UITextField alloc] initWithFrame:CGRectZero];
    f.tag = 2002;
    f.text = SettingString(kSsid, @"");
    f.placeholder = @"e.g. MyHomeWiFi";
    f.autocorrectionType = UITextAutocorrectionTypeNo;
    f.autocapitalizationType = UITextAutocapitalizationTypeNone;
    f.returnKeyType = UIReturnKeyDone;
    f.delegate = self;
    [cell.contentView addSubview:f];
    [f setContentHuggingPriority:UILayoutPriorityRequired
                          forAxis:UILayoutConstraintAxisHorizontal];
    [f setContentCompressionResistancePriority:UILayoutPriorityDefaultLow
                                        forAxis:UILayoutConstraintAxisHorizontal];
    [NSLayoutConstraint activateConstraints:@[
      [f.centerYAnchor constraintEqualToAnchor:cell.contentView.centerYAnchor],
      [f.leadingAnchor constraintEqualToAnchor:cell.textLabel.trailingAnchor constant:12],
      [f.trailingAnchor constraintEqualToAnchor:cell.contentView.trailingAnchor constant:-16],
    ]];
    return cell;
  }

  NSString* cellId = [NSString stringWithFormat:@"c%ld-%ld", (long)ip.section, (long)ip.row];
  UITableViewCell* cell = [tableView dequeueReusableCellWithIdentifier:cellId];
  if (!cell) {
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:cellId];
  }
  cell.selectionStyle = UITableViewCellSelectionStyleNone;
  cell.accessoryView = nil;
  cell.accessoryType = UITableViewCellAccessoryNone;
  cell.textLabel.text = @"";
  cell.detailTextLabel.text = @"";

  if (ip.section == 2) {
    switch (ip.row) {
      case 0: {
        cell.textLabel.text = @"Certificate valid until";
        cell.detailTextLabel.text = SslNotAfterString();
        break;
      }
      case 1: {
        cell.textLabel.text = @"Update SSL servers";
        cell.textLabel.textColor = [UIColor systemBlueColor];
        cell.accessoryType = self.busy ? UITableViewCellAccessoryNone
                                       : UITableViewCellAccessoryDisclosureIndicator;
        if (self.busy) {
          UIActivityIndicatorView* spin =
              [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];
          [spin startAnimating];
          cell.accessoryView = spin;
        }
        cell.selectionStyle = UITableViewCellSelectionStyleDefault;
        break;
      }
    }
  } else if (ip.section == 3) {
    cell.textLabel.text = @"Install proxy profile (.mobileconfig)";
    cell.textLabel.textColor = [UIColor systemBlueColor];
    cell.selectionStyle = UITableViewCellSelectionStyleDefault;
    if (self.busy) {
      UIActivityIndicatorView* spin =
          [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];
      [spin startAnimating];
      cell.accessoryView = spin;
    }
  } else if (ip.section == 4) {
    cell.textLabel.text = @"Keep i2pd alive in background";
    UISwitch* sw = [[UISwitch alloc] init];
    sw.tag = 3000;
    sw.on = SettingBool(kKeepAlive, NO);
    [sw addTarget:self action:@selector(keepAliveChanged:) forControlEvents:UIControlEventValueChanged];
    cell.accessoryView = sw;
  }
  return cell;
}

- (void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)ip {
  if (ip.section == 2 && ip.row == 1) {
    [self updateSslServers];
  } else if (ip.section == 3) {
    [self installProfile];
  }
  [tableView deselectRowAtIndexPath:ip animated:YES];
}

- (void)keepAliveChanged:(UISwitch*)sw {
  [UD() setBool:sw.on forKey:kKeepAlive];
  [[KeepAlive shared] apply];
}

- (void)textFieldDidEndEditing:(UITextField*)field {
  switch (field.tag) {
    case 2000: {
      NSString* h = [field.text stringByTrimmingCharactersInSet:
          [NSCharacterSet whitespaceCharacterSet]];
      if (!h.length) h = @"ios2pd.backloop.dev";
      field.text = h;
      [UD() setObject:h forKey:kBackloopHost];
      break;
    }
    case 2001: {
      int port = [field.text intValue];
      if (port < 1 || port > 65535) port = 8443;
      field.text = [NSString stringWithFormat:@"%d", port];
      [UD() setInteger:port forKey:kBackloopPort];
      break;
    }
    case 2002: {
      NSString* ssid = [field.text stringByTrimmingCharactersInSet:
          [NSCharacterSet whitespaceCharacterSet]];
      field.text = ssid;
      [UD() setObject:ssid forKey:kSsid];
      break;
    }
  }
}

- (BOOL)textFieldShouldReturn:(UITextField*)field {
  [field resignFirstResponder];
  return YES;
}

- (void)alert:(NSString*)message {
  UIAlertController* a = [UIAlertController alertControllerWithTitle:@"ios2pd"
                                                              message:message
                                                       preferredStyle:UIAlertControllerStyleAlert];
  [a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];
  [self presentViewController:a animated:YES completion:nil];
}

- (void)updateSslServers {
  [self updateBusy:YES];
  dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
    NSError* e = nil;
    BOOL ok = SslRefresh(&e);
    dispatch_async(dispatch_get_main_queue(), ^{
      [self updateBusy:NO];
      [self alert:ok ? @"SSL certificate updated from backloop.dev."
                     : [NSString stringWithFormat:@"Update failed: %@",
                                                   e.localizedDescription ?: @"unknown error"]];
    });
  });
}

- (void)doInstall {
  NSString* ssid = SettingString(kSsid, @"");
  if (!ssid.length) {
    [self alert:@"Enter your Wi-Fi SSID first (Proxy tab > Wi-Fi network)."];
    return;
  }
  int port = SettingInt(kBackloopPort, 8443);
  NSString* host = SettingString(kBackloopHost, @"ios2pd.backloop.dev");
  SslServerStart(port);
  NSString* url = [NSString stringWithFormat:@"https://%@:%d/install.mobileconfig", host, port];
  [[UIApplication sharedApplication] openURL:[NSURL URLWithString:url]
                                     options:@{}
                           completionHandler:^(BOOL ok) {
                             if (!ok) {
                               [self alert:
                                   @"Could not open Safari. Make sure the app is "
                                   @"running and Wi-Fi is available."];
                             }
                           }];
}

- (void)installProfile {
  if (self.busy) return;
  if (!SslHasCert()) {
    [self updateBusy:YES];
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
      NSError* e = nil;
      BOOL ok = SslRefresh(&e);
      dispatch_async(dispatch_get_main_queue(), ^{
        [self updateBusy:NO];
        if (!ok) {
          [self alert:[NSString stringWithFormat:@"SSL setup failed: %@",
                                                  e.localizedDescription ?: @"unknown error"]];
          return;
        }
        [self doInstall];
      });
    });
  } else {
    [self doInstall];
  }
}

@end

// ---------------------------------------------------------------------------
// App delegate
// ---------------------------------------------------------------------------
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow* window;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication*)application
    didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {
  [[KeepAlive shared] apply];

  UINavigationBarAppearance* navAppearance = [[UINavigationBarAppearance alloc] init];
  [navAppearance configureWithTransparentBackground];
  navAppearance.backgroundEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleSystemMaterial];
  [UINavigationBar appearance].standardAppearance = navAppearance;
  [UINavigationBar appearance].scrollEdgeAppearance = navAppearance;
  [UINavigationBar appearance].prefersLargeTitles = YES;

  UITabBarAppearance* tabAppearance = [[UITabBarAppearance alloc] init];
  [tabAppearance configureWithTransparentBackground];
  tabAppearance.backgroundEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleSystemMaterial];
  [UITabBar appearance].standardAppearance = tabAppearance;
  if (@available(iOS 15.0, *)) {
    [UITabBar appearance].scrollEdgeAppearance = tabAppearance;
  }
  [UITabBar appearance].tintColor = [UIColor systemBlueColor];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];

  RouterViewController* router = [[RouterViewController alloc] init];
  router.title = @"Router";
  router.tabBarItem.image = [UIImage systemImageNamed:@"network"];

  TunnelsViewController* tunnels = [[TunnelsViewController alloc] init];
  tunnels.title = @"Tunnels";
  tunnels.tabBarItem.image = [UIImage systemImageNamed:@"arrow.up.arrow.down"];

  I2pdSettingsViewController* i2pd = [[I2pdSettingsViewController alloc] init];
  i2pd.title = @"i2pd";
  i2pd.tabBarItem.image = [UIImage systemImageNamed:@"switch.2"];

  AppSettingsViewController* proxy = [[AppSettingsViewController alloc] init];
  proxy.title = @"Proxy";
  proxy.tabBarItem.image = [UIImage systemImageNamed:@"globe"];

  UINavigationController* n1 = [[UINavigationController alloc] initWithRootViewController:router];
  UINavigationController* n2 = [[UINavigationController alloc] initWithRootViewController:tunnels];
  UINavigationController* n3 = [[UINavigationController alloc] initWithRootViewController:i2pd];
  UINavigationController* n4 = [[UINavigationController alloc] initWithRootViewController:proxy];

  UITabBarController* tbc = [[UITabBarController alloc] init];
  tbc.viewControllers = @[ n1, n2, n3, n4 ];

  self.window.rootViewController = tbc;
  [self.window makeKeyAndVisible];
  return YES;
}

- (void)applicationWillTerminate:(UIApplication*)application {
  StopDaemon();
}

- (void)applicationDidEnterBackground:(UIApplication*)application {
  [[KeepAlive shared] apply];
}

- (void)applicationDidBecomeActive:(UIApplication*)application {
  [[KeepAlive shared] apply];
}

@end

int main(int argc, char* argv[]) {
  @autoreleasepool {
    OPENSSL_init_ssl(0, NULL);
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}
